(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.Artwork47ai = function() {
	this.initialize(img.Artwork47ai);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,824,917);


(lib.Play_Button = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Artwork47ai();
	this.instance.parent = this;
	this.instance.setTransform(-41.9,-46.6,0.102,0.102);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.9,-46.6,83.9,93.3);


// stage content:
(lib.NEWanimateBanner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		this.Play_Button.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame()
		{
			this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(115));

	// Layer 5
	this.Play_Button = new lib.Play_Button();
	this.Play_Button.parent = this;
	this.Play_Button.setTransform(600.9,75,0.954,0.954);
	new cjs.ButtonHelper(this.Play_Button, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.Play_Button).to({_off:true},1).wait(114));

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#B79CAA").ss(18,1,1).p("Al2naILtAAQApAAAdAeQAeAdAAApIAALtQAAApgeAdQgdAegpAAIrtAAQgpAAgdgeQgegdAAgpIAArtQAAgpAegdQAdgeApAAg");
	this.shape.setTransform(600,75,1.264,1.265);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#B79CAA").ss(17.7,1,1).p("ApKnPQAAgzAkglQAlgkAzAAIOeAAQAzAAAkAkQAkAlAAAzIAAOfQAAA0gkAkQgkAkgzAAIueAAQgzAAglgkQgkgkAAg0g");
	this.shape_1.setTransform(600,75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#B79CAA").ss(17.3,1,1).p("Ao+nFQAAgyAkgkQAkgkAxAAIOLAAQAyAAAjAkQAkAkAAAyIAAOLQAAAygkAjQgjAlgyAAIuLAAQgxAAgkglQgkgjAAgyg");
	this.shape_2.setTransform(600,75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#B79CAA").ss(17,1,1).p("Aoxm8QAAgwAigjQAkgjAwAAIN3AAQAxAAAjAjQAiAjAAAwIAAN5QAAAwgiAjQgjAjgxAAIt3AAQgwAAgkgjQgigjAAgwg");
	this.shape_3.setTransform(600,75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#B79CAA").ss(16.6,1,1).p("AolmyQAAgvAigiQAjgjAvAAINjAAQAwAAAiAjQAiAiAAAvIAANkQAAAwgiAiQgiAjgwAAItjAAQgvAAgjgjQgigiAAgwg");
	this.shape_4.setTransform(600,75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#B79CAA").ss(16.3,1,1).p("AoYmoQAAguAhgiQAighAuAAINPAAQAvAAAhAhQAhAiAAAuIAANRQAAAvghAhQghAhgvAAItPAAQguAAgighQghghAAgvg");
	this.shape_5.setTransform(600,75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#B79CAA").ss(15.9,1,1).p("AoMmeQAAguAhggQAgghAuAAIM8AAQAuAAAfAhQAhAgAAAuIAAM9QAAAughAgQgfAhguAAIs8AAQguAAggghQghggAAgug");
	this.shape_6.setTransform(600,75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#B79CAA").ss(15.6,1,1).p("An/mUQAAgtAfgfQAgggAtAAIMoAAQAtAAAfAgQAfAfAAAtIAAMpQAAAtgfAfQgfAggtAAIsoAAQgtAAggggQgfgfAAgtg");
	this.shape_7.setTransform(600,75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#B79CAA").ss(15.2,1,1).p("AnzmKQAAgsAfgeQAfggAsAAIMUAAQAsAAAeAgQAfAeAAAsIAAMVQAAAsgfAeQgeAggsAAIsUAAQgsAAgfggQgfgeAAgsg");
	this.shape_8.setTransform(600,75);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#B79CAA").ss(14.9,1,1).p("AnmmAQAAgrAegeQAegeArAAIMAAAQArAAAdAeQAeAeAAArIAAMBQAAArgeAeQgdAegrAAIsAAAQgrAAgegeQgegeAAgrg");
	this.shape_9.setTransform(600,75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#B79CAA").ss(14.5,1,1).p("Anal2QAAgqAegdQAdgeApAAILtAAQAqAAAdAeQAdAdAAAqIAALtQAAAqgdAdQgdAegqAAIrtAAQgpAAgdgeQgegdAAgqg");
	this.shape_10.setTransform(600,75);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#B79CAA").ss(14.2,1,1).p("AnNltQAAgoAcgcQAdgdAoAAILZAAQApAAAcAdQAcAcAAAoIAALbQAAAogcAcQgcAdgpAAIrZAAQgoAAgdgdQgcgcAAgog");
	this.shape_11.setTransform(600,75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#B79CAA").ss(13.9,1,1).p("AnBljQAAgnAcgcQAcgcAnAAILFAAQAoAAAbAcQAcAcAAAnIAALHQAAAngcAcQgbAcgoAAIrFAAQgnAAgcgcQgcgcAAgng");
	this.shape_12.setTransform(600,75);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#B79CAA").ss(13.5,1,1).p("Am0lZQAAgmAbgbQAbgbAmAAIKyAAQAmAAAaAbQAbAbAAAmIAAKzQAAAmgbAbQgaAbgmAAIqyAAQgmAAgbgbQgbgbAAgmg");
	this.shape_13.setTransform(600,75);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#B79CAA").ss(13.2,1,1).p("AmolPQAAglAbgaQAagbAlAAIKeAAQAlAAAaAbQAaAaAAAlIAAKfQAAAlgaAaQgaAbglAAIqeAAQglAAgagbQgbgaAAglg");
	this.shape_14.setTransform(600,75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#B79CAA").ss(12.8,1,1).p("AmblFQAAgkAZgZQAagaAkAAIKKAAQAkAAAZAaQAZAZAAAkIAAKLQAAAkgZAZQgZAagkAAIqKAAQgkAAgagaQgZgZAAgkg");
	this.shape_15.setTransform(600,75);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#B79CAA").ss(12.5,1,1).p("AmPk7QAAgjAZgZQAZgZAjAAIJ2AAQAjAAAYAZQAZAZAAAjIAAJ3QAAAjgZAZQgYAZgjAAIp2AAQgjAAgZgZQgZgZAAgjg");
	this.shape_16.setTransform(600,75);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#B79CAA").ss(12.1,1,1).p("AmCkxQAAgiAYgYQAYgYAiAAIJiAAQAiAAAYAYQAXAYAAAiIAAJjQAAAigXAXQgYAZgiAAIpiAAQgiAAgYgZQgYgXAAgig");
	this.shape_17.setTransform(600,75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#B79CAA").ss(11.8,1,1).p("Al2knQAAghAYgXQAXgYAgAAIJPAAQAhAAAXAYQAXAXAAAhIAAJPQAAAhgXAXQgXAYghAAIpPAAQggAAgXgYQgYgXAAghg");
	this.shape_18.setTransform(600,75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#B79CAA").ss(11.4,1,1).p("AlpkeQAAgfAWgWQAXgXAfAAII7AAQAgAAAWAXQAWAWAAAfIAAI9QAAAfgWAWQgWAXggAAIo7AAQgfAAgXgXQgWgWAAgfg");
	this.shape_19.setTransform(600,75);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#B79CAA").ss(11.1,1,1).p("AldkUQAAgeAWgWQAWgWAeAAIIoAAQAeAAAVAWQAWAWAAAeIAAIpQAAAegWAVQgVAXgeAAIooAAQgeAAgWgXQgWgVAAgeg");
	this.shape_20.setTransform(600,75);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#B79CAA").ss(10.7,1,1).p("AlQkKQAAgdAVgVQAVgVAdAAIIUAAQAdAAAVAVQAUAVAAAdIAAIVQAAAdgUAVQgVAVgdAAIoUAAQgdAAgVgVQgVgVAAgdg");
	this.shape_21.setTransform(600,75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#B79CAA").ss(10.4,1,1).p("AlEkAQAAgcAVgUQAUgVAcAAIIAAAQAcAAAUAVQAUAUAAAcIAAIBQAAAcgUAUQgUAVgcAAIoAAAQgcAAgUgVQgVgUAAgcg");
	this.shape_22.setTransform(600,75);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#B79CAA").ss(10,1,1).p("Ak4j2QAAgbAUgTQATgUAcAAIHsAAQAbAAATAUQAUATAAAbIAAHtQAAAbgUATQgTAUgbAAInsAAQgcAAgTgUQgUgTAAgbg");
	this.shape_23.setTransform(600,75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#B79CAA").ss(9.7,1,1).p("AkrjsQAAgaATgTQASgSAbAAIHYAAQAaAAASASQATATAAAaIAAHZQAAAagTATQgSASgaAAInYAAQgbAAgSgSQgTgTAAgag");
	this.shape_24.setTransform(600,75);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#B79CAA").ss(9.3,1,1).p("AkfjiQAAgZASgSQATgSAYAAIHFAAQAZAAASASQASASAAAZIAAHFQAAAagSARQgSASgZAAInFAAQgYAAgTgSQgSgRAAgag");
	this.shape_25.setTransform(600,75);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#B79CAA").ss(9,1,1).p("AkSjYQAAgYARgRQASgRAXAAIGxAAQAYAAARARQARARAAAYIAAGxQAAAZgRAQQgRARgYAAImxAAQgXAAgSgRQgRgQAAgZg");
	this.shape_26.setTransform(600,75);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#B79CAA").ss(8.6,1,1).p("AkGjOQAAgXARgRQAQgQAXAAIGeAAQAWAAAQAQQARARAAAXIAAGdQAAAXgRARQgQAQgWAAImeAAQgXAAgQgQQgRgRAAgXg");
	this.shape_27.setTransform(600,75);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#B79CAA").ss(8.3,1,1).p("Aj5jFQAAgVAPgQQAQgPAWAAIGKAAQAVAAAQAPQAPAQAAAVIAAGLQAAAWgPAPQgQAPgVAAImKAAQgWAAgQgPQgPgPAAgWg");
	this.shape_28.setTransform(600,75);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#B79CAA").ss(7.9,1,1).p("Ajti7QAAgVAPgOQAPgPAUAAIF3AAQAVAAAOAPQAPAOAAAVIAAF3QAAAUgPAPQgOAPgVAAIl3AAQgUAAgPgPQgPgPAAgUg");
	this.shape_29.setTransform(600,75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#B79CAA").ss(7.6,1,1).p("AjgixQAAgUAOgNQAOgOATAAIFjAAQAUAAANAOQAOANAAAUIAAFjQAAAUgOANQgNAOgUAAIljAAQgTAAgOgOQgOgNAAgUg");
	this.shape_30.setTransform(600,75);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#B79CAA").ss(7.2,1,1).p("AjUinQAAgTAOgNQANgNASAAIFPAAQASAAAOANQANANAAATIAAFPQAAATgNANQgOANgSAAIlPAAQgSAAgNgNQgOgNAAgTg");
	this.shape_31.setTransform(600,75);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#B79CAA").ss(6.9,1,1).p("AjHidQAAgRAMgNQANgMARAAIE7AAQARAAANAMQAMANAAARIAAE7QAAARgMANQgNAMgRAAIk7AAQgRAAgNgMQgMgNAAgRg");
	this.shape_32.setTransform(600,75);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#B79CAA").ss(6.5,1,1).p("Ai7iTQAAgRANgLQALgMAQAAIEnAAQARAAALAMQAMALAAARIAAEnQAAARgMALQgLAMgRAAIknAAQgQAAgLgMQgNgLAAgRg");
	this.shape_33.setTransform(600,75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#B79CAA").ss(6.2,1,1).p("AiuiJQAAgQALgKQALgLAPAAIEUAAQAPAAAKALQALAKAAAQIAAETQAAAPgLALQgKALgPAAIkUAAQgPAAgLgLQgLgLAAgPg");
	this.shape_34.setTransform(600,75);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#B79CAA").ss(5.9,1,1).p("Aiih/QAAgPALgKQAKgKAOAAIEAAAQAOAAAKAKQAKAKAAAPIAAD/QAAAPgKAKQgKAKgOAAIkAAAQgOAAgKgKQgLgKAAgPg");
	this.shape_35.setTransform(600,75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#B79CAA").ss(5.5,1,1).p("AiVh2QAAgNAKgJQAJgJANAAIDsAAQAMAAAJAJQAKAJAAANIAADsQAAAOgKAJQgJAJgMAAIjsAAQgNAAgJgJQgKgJAAgOg");
	this.shape_36.setTransform(600,75);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#B79CAA").ss(5.2,1,1).p("AiJhrQAAgMAJgJQAJgJALAAIDZAAQALAAAJAJQAJAJAAAMIAADXQAAAMgJAJQgJAJgLAAIjZAAQgLAAgJgJQgJgJAAgMg");
	this.shape_37.setTransform(600,75);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#B79CAA").ss(4.8,1,1).p("Ah8hhQAAgMAIgIQAIgHAKAAIDFAAQALAAAHAHQAIAIAAAMIAADDQAAAMgIAIQgHAHgLAAIjFAAQgKAAgIgHQgIgIAAgMg");
	this.shape_38.setTransform(600,75);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#B79CAA").ss(4.5,1,1).p("AhwhXQAAgKAIgHQAHgIAJAAICxAAQAKAAAGAIQAIAHAAAKIAACvQAAALgIAGQgGAIgKAAIixAAQgJAAgHgIQgIgGAAgLg");
	this.shape_39.setTransform(600,75);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#B79CAA").ss(4.1,1,1).p("AhjhOQAAgJAGgGQAHgGAIAAICdAAQAJAAAGAGQAGAGAAAJIAACdQAAAJgGAGQgGAGgJAAIidAAQgIAAgHgGQgGgGAAgJg");
	this.shape_40.setTransform(600,75);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#B79CAA").ss(3.8,1,1).p("AhXhEQAAgIAHgFQAFgGAHAAICKAAQAHAAAFAGQAGAFAAAIIAACJQAAAIgGAFQgFAGgHAAIiKAAQgHAAgFgGQgHgFAAgIg");
	this.shape_41.setTransform(600,75);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("#B79CAA").ss(3.4,1,1).p("AhKg6QAAgHAFgEQAFgFAGAAIB2AAQAGAAAEAFQAFAEAAAHIAAB1QAAAHgFAEQgEAFgGAAIh2AAQgGAAgFgFQgFgEAAgHg");
	this.shape_42.setTransform(600,75);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#B79CAA").ss(3.1,1,1).p("Ag+gwQAAgGAFgDQADgFAGAAIBiAAQAFAAAEAFQAEADAAAGIAABhQAAAGgEADQgEAFgFAAIhiAAQgGAAgDgFQgFgDAAgGg");
	this.shape_43.setTransform(600,75);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("#B79CAA").ss(2.7,1,1).p("AgxgnQAAgEAEgDQACgDAFAAIBOAAQAEAAADADQADADAAAEIAABPQAAAEgDADQgDADgEAAIhOAAQgFAAgCgDQgEgDAAgEg");
	this.shape_44.setTransform(600,75);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f().s("#B79CAA").ss(2.4,1,1).p("AglgdQAAgDADgCQACgDADAAIA7AAQADAAACADQADACAAADIAAA7QAAADgDACQgCADgDAAIg7AAQgDAAgCgDQgDgCAAgDg");
	this.shape_45.setTransform(600,75);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f().s("#B79CAA").ss(2,1,1).p("Al2naILtAAQApAAAdAeQAeAdAAApIAALtQAAApgeAdQgdAegpAAIrtAAQgpAAgdgeQgegdAAgpIAArtQAAgpAegdQAdgeApAAg");
	this.shape_46.setTransform(600,75,0.053,0.053);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_46}]},48).wait(20));

	// Layer 3
	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#B79CAA").s().p("EAGxAo9Imx0nIm4UnI6zAAQjAAAiJiIQiIiJAAjAIAA4TQAAhKArg7QAqg8BGgYIR/mDI0amxIAA63QAAjACIiJQCJiIDAAAIabAAIHQU2IHR02IabAAQDAAACJCIQCICJAADAIAAa3I0jGxIUjG4IAAa3QAADAiICJQiJCIjAAAgAABOGQCCAABoBMQBpBMAoB7IFWQUIWaAAQAaAAAUgTQATgUAAgaIAA2XIwSleQh7gphLhpQhLhpAAiBQABiBBLhoQBMhpB7goIQQlWIAA2WQAAgagTgUQgUgTgaAAI1/AAIlzQpQgqB5hoBKQhoBKiAAAQh/AAhohKQhohKgqh5IlzwpI1/AAQgaAAgUATQgTAUAAAaIAAWWIQIFWQB6AoBMBpQBMBoAACBQABCAhLBpQhMBqh6ApIwKFdIAAWYQAAAaATAUQAUATAaAAIWTAAIFewWQAph6BohMQBphLCAAAg");
	this.shape_47.setTransform(600,75,0.01,0.01);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#B79CAA").s().p("AAFAeIgFgPIgEAPIgUAAIgEgCIAAgDIAAgSIAAgBIABgCIANgEIgOgEIAAgUIAAgDIAEgCIAUAAIAEAPIAFgPIAUAAIADACQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIAAAUIgOAEIAOAFIAAAUQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAIgDACgAAAALIABAAIABAAIABABIACACIACAIIABADIAOAAIABAAIAAAAIACAAIAAgPIAAgCIgLgDIgBgBIgCAAIgBgBIAAgCIAAgBIABAAIAAgCIADgCIAJgCIACgCIAAgNIAAgCIAAgBIgPAAIgCAAIgEALIAAACIgCABIgCABIgCgBIgCgDIgEgLIgQAAIgBAAIAAAQIABABIAMAEIACABIABACIAAACIgBABIAAAAIgDACIgJADIgDABIAAANIAAABIABABIAAABIAAAAIAPAAIACAAIAEgLIAAgBIABgBIABgBIAAAAIABAAIAAAAg");
	this.shape_48.setTransform(600,75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#B79CAA").s().p("AAGAjIgGgSIgFASIgXAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgUIAAgCIACgBIAPgFIgRgFIAAgWQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAIAXAAIAFASIAGgSIAWAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAABIAAAWIgRAFIARAFIAAAXQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgBAMIABAAIABAAIABABIACABIACADIACAJIACADIAPAAIABAAIABgBIACAAIAAgRIgBgBIgMgFIgBgBIgBgBIgBgBIgCgBIAAgBIACgBIABgCIACgCIALgCIACgCIAAgQIgBgCIAAgBIgRAAIgCABIgEALIgBADIgCABIgCABIgDgCIgBgDIgFgMIgTAAIAAABIAAATIANADIAAABIADABIAAABIABACIAAABIAAABIgBABIgBABIgDABIgLAEIgBABIAAAQIAAABIAAABIAAAAIABABIARAAIABgBIAFgMIAAgBIACgCIABgBg");
	this.shape_49.setTransform(600,75);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#B79CAA").s().p("AAGAnIgGgTIgGATIgZAAQgDAAgCgCQgCgCAAgDIAAgXIAAgCIACgBIARgGIgTgFIAAgaQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQACgCADAAIAZAAIAGAUIAGgUIAaAAQACAAACACQADACAAADIAAAaIgUAFIAUAHIAAAZQAAADgDACQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAgAAAAOIACABIABAAIABACIACADIADAKIADADIARAAIABAAIABAAIACgCIAAgSIgCgCIgNgFIgCgBIgBgBIgBgBIgBgCIAAgBIABgBIABgCIADgCIANgEIACgCIAAgRIgBgDIgBgBIgSAAIgDABIgFAOIgBADIgCABIgDABIgDgCIgCgEIgFgOIgVAAIAAABIAAAVIAAABIAPAEIADADIABACIAAABIAAACIgCABIAAABIgEABIgMAEIgBADIAAARIAAABIAAABIAAABIACAAIASAAIACgBIAFgOIAAgBIACgCIACgBIAAAAIABAAIAAAAg");
	this.shape_50.setTransform(600,75);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#B79CAA").s().p("AAHAsIgHgWIgHAWIgcAAQgDAAgCgDQgDgCAAgDIAAgaIABgCIACgBIAUgHIgXgGIAAgdQAAgDADgCQACgDADAAIAcAAIAHAXIAIgXIAbAAQADAAADADQACACAAADIAAAdIgVAGIAVAHIAAAdQAAADgCACQgDADgDAAgAABAQIACABIABABIACABIABAEIAEAMIAEACIASAAIACAAIAAAAIABgCIAAgVIgBgCIgPgFIgCgBIgBgBIgBgCIgBgCIAAgBIABgCIACgCIAEgCIANgEIABgDIAAgTIAAgDIgBgBIgVAAIgCABIgFAQIgCADIgEACIgCAAIgDgCIgJgUIgXAAIAAABIAAAXIAAABIARAGIAAAAIADACIABAAIAAADIAAABIAAACIgCACIAAABIgEABIgOAFIgBACIAAAUIAAABIAAABIABABIABAAIAVAAIACgBIAFgQIAAgBIADgCIACgBIAAAAIABAAIABAAg");
	this.shape_51.setTransform(600,75);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#B79CAA").s().p("AAIAwIgIgYIgHAYIgfAAQgEAAgDgCQgCgDAAgDIAAgdIABgCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAVgHIgYgHIAAggQAAgDACgDQADgCAEAAIAeAAIAIAYIAIgYIAgAAQADAAACACQADADAAADIAAAgIgYAHIAYAIIAAAgQAAADgDADQgCACgDAAgAAAARIACABIACABIABABIACACIABADIAEAOIAEACIAVAAIABAAIABgBIACgCIAAgXIgDgCIgQgGIgCAAIgCgCIgBgCIgBgCIAAgBIABgCIADgDIAEgCIAPgEIACgDIAAgWIgBgDIgCgBIgXAAIgCACIgGARIgBAEIgFABIgCAAIgDgCIgDgFIgIgRIgYABIgBAAIAAAaIABABIASAGIABAAQAAAAAAABQABAAAAAAQABAAAAABQABAAAAABIABADIAAABIgBADIgCACIAAAAIgFACIgOAFIgCADIAAAWIABABIAAABIABABIABAAIAXAAIACgCIAGgRIAAgBIACgCIADgCIABAAg");
	this.shape_52.setTransform(600,75);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#B79CAA").s().p("AAIA1IgIgaIgIAaIgjAAQgDAAgDgDQgDgCAAgEIAAggIABgCIADgCIAXgIIgbgIIAAgiQAAgEADgDQADgDADAAIAjAAIAIAbIAJgbIAiAAQAEAAADADQACADABAEIAAAiIgbAIIAbAJIAAAjQgBAEgCACQgDADgEAAgAAAATIACAAIADACIABABIABACIACAEIAFAPIAEACIAXAAIACAAIAAgBIABgDIAAgYIgBgDIgSgGIgDgBIgCgCIgBgCIgBgCIAAgBIABgDIADgDIAEgCIARgFIABgDIAAgZIgBgCIgBgBIgaAAIgBACIgHASIgCAFIgFACIgDgBQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAgBgBIgKgXIgbABIgBABIAAAbIABABIAUAHIABAAIADADIAAAAIABAEIAAABIgBADIgBACIgBABIgFACIgQAFIgCAEIAAAXIAAACIABABIABABIACAAIAZAAIACgCIAGgSIAAgDIADgCQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAIABAAg");
	this.shape_53.setTransform(600,75);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#B79CAA").s().p("AAJA6IgJgdIgJAdIglAAQgEAAgEgDQgCgDAAgEIAAgjIABgCIACgCIAZgJIgcgJIAAglQAAgFACgCQAEgEAEAAIAlAAIAJAeIAKgeIAlAAQAEAAADAEQADACAAAFIAAAlIgdAJIAdAKIAAAmQAAAEgDADQgDADgEAAgAAAAUIADABIADADIABAAIABADIACAEIAFAQIAFACIAZAAIABAAIABgBIACgDIAAgbIgDgDIgUgGIgCgBIgCgCIgCgCIgBgDIABgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIADgDIAEgDIASgFIACgEIAAgaIgCgDIgCgBIgbAAIgCADIgIAUIgCAEIgFACIgDAAIgEgDIgDgGIgJgUIgdABIAAABIAAAfIABABIAVAHIAAAAIAFADIAAAAIABAEIAAABIgBADIgCADIgCABIgEACIgSAFIgBAFIAAAaIAAABIABABIAAAAIACABIAbAAIACgCIAHgUIABgCIADgDIADgCIABAAg");
	this.shape_54.setTransform(600,75);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#B79CAA").s().p("AAKA+IgKgfIgKAfIgoAAQgEAAgEgDQgDgDAAgFIAAglIABgDIADgCIAbgJIgfgJIAAgpQAAgFADgDQAEgDAEAAIAoAAIAKAgIALggIAoAAQAEAAADADQAEADAAAFIAAApIgfAJIAfALIAAAoQAAAFgEADQgDADgEAAgAAAAWIADABIADADIABAAIACADIACAFIAFARIAGACIAbAAIABgBIABAAIABgEIAAgdIgDgCIgVgIIgCgBIgDgCIgBgCIgBgDIAAgBIACgEIADgDIAFgCIAUgGIABgFIAAgcIgBgDIgCgBIgeAAIgDADIgHAWIgDAFIgFACQgCAAgCgBQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgDgGIgJgWIggABIgBABIAAAhIABABIAYAIIAAAAIAFADIAAABQABACAAACIAAACIgBADIgDADIgBAAIgGADIgSAGIgCAEIAAAdIABABIAAABIABAAIACABIAeAAIACgDIAIgVIAAgCIADgDIAEgCIABAAg");
	this.shape_55.setTransform(600,75);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#B79CAA").s().p("AALBDIgLghIgKAhIgsAAQgEAAgEgDQgDgEAAgFIAAgnIAAgEIADgCIAegKIghgKIAAgsQAAgFADgDQAEgEAEAAIArAAIALAiIALgiIArAAQAFAAAEAEQADADAAAFIAAAsIghAKIAhALIAAAsQAAAFgDAEQgEADgFAAgAAAAXIAEACIADADIABAAIABADIADAGIAFASIAHABIAdAAIABAAIABgBIABgEIAAgfIgDgCIgXgIIgDgBIgCgCIgBgDIgBgDIAAgBIACgFIADgDIAGgCIAVgHIABgFIAAgeIgBgDIgDAAIggAAIgCADIgJAWIgCAFQgDADgDAAQgCABgDgCQgCgBgCgCIgCgHIgLgWIgiAAIAAABIAAAkIABABIAZAIIAAABQADAAACADIAAAAQACADAAACIgBACIgBADIgDADIgBABIgGACIgUAHIgBAFIAAAfIAAABIABABIABAAIACAAIAgAAIACgCIAIgYIABgCIADgCQAAgBABAAQAAgBABAAQAAAAABAAQABgBAAAAIABAAg");
	this.shape_56.setTransform(600,75);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#B79CAA").s().p("AALBIIgLgkIgLAkIguAAQgGAAgDgEQgEgEAAgFIAAgqIABgEQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAIAegLIgjgLIAAgvQAAgFAEgEQADgEAGAAIAuAAIALAlIANglIAuAAQAEAAAFAEQADAEAAAFIAAAvIgkALIAkAMIAAAvQAAAFgDAEQgFAEgEAAgAAAAZIAFABQACACABACIABABIABADIADAFIAGAUIAHACIAeAAIADgBIAAgBIABgEIAAgiIgEgCIgXgIIgEgCIgCgCIgCgCIAAgEIAAgBQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAAAgBQACgCADgCIAFgCIAXgHIABgFIAAghIgBgDIgDAAIgiAAIgDADIgJAZIgCAFIgHADQgCAAgDgCQgCgBgCgCIgDgHIgLgYIgkAAIgBABIAAAnIABABIAbAJIABAAIAEAEIABAAIABAFIAAACIgCAEQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAIgCABIgHADIgVAGIgBAGIAAAhIABABIAAABIACAAIACABIAiAAIACgDIAJgZIAAgCIADgEQADgCADAAIAAAAg");
	this.shape_57.setTransform(600,75);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#B79CAA").s().p("AANBMIgNgmIgLAmIgyAAQgGAAgEgEQgDgEAAgFIAAgtIABgEQAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAhgLIglgLIAAgyQAAgGADgEQAEgEAGAAIAxAAIAMAnIAOgnIAwAAQAGAAADAEQAEAEABAGIAAAyIgnALIAnANIAAAyQgBAFgEAEQgDAEgGAAgAAAAbIAFABQACACABACIABABIACAEIADAFIAGAVIAIACIAhAAIABgBIABgBIABgFIAAgjIgEgDIgZgJIgDgBIgDgDIgCgCIgBgEIAAgBIACgFIAFgEIAGgDIAYgHIABgGIAAgjIgCgDIgCAAIglAAIgDADIgJAbQgBACgCAEQgDACgEAAQgCABgDgCIgFgEIgCgIIgNgZIgnABIAAABIAAApIABABIAdAJIAAAAIAFAEIABABQACACgBADIAAACIgBAEIgDAEIgCABIgHACIgXAIIgBAGIAAAjIAAABIABABIACAAIADABIAkAAIACgEIAJgaIABgCIADgEQACgCAEAAIAAAAg");
	this.shape_58.setTransform(600,75);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#B79CAA").s().p("AANBRIgNgpIgNApIg0AAQgGAAgEgFQgEgDAAgHIAAgvIABgFQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAIAjgMIgogNIAAg1QAAgFAEgFQAEgEAGAAIA0AAIANApIAOgpIA0AAQAGAAAEAEQAEAFAAAFIAAA1IgoANIAoANIAAA1QAAAHgEADQgEAFgGAAgAABAcIAFACQACACABACIABABIACAEIACAGIAHAWIAJABIAiAAIACAAIABgBIABgGIAAgmIgFgCIgbgJIgDgCIgDgCIgBgDIgBgEIAAgBIACgGQACgDADgBIAHgDIAZgIIABgGIAAglIgCgDIgDgBIgnAAIgDAFIgJAcIgEAGQgDACgEABQgDAAgDgCQgDgCgBgDIgEgHIgNgcIgoABIgBABIAAAsIACABIAeAKIABABIAFADIAAABQACADAAADIAAACIgCAFIgEADIgBABIgIADIgYAIIgBAGIAAAlIABACIABABIABAAIADAAIAnAAIACgDIAJgcIABgCIAEgFQACgCAEAAIABAAg");
	this.shape_59.setTransform(600,75);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#B79CAA").s().p("AAOBVIgOgqIgOAqIg3AAQgGABgFgFQgEgFAAgFIAAg0QAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAgBIAlgMIgqgOIAAg4QAAgFAEgFQAFgFAGAAIA3AAIAOAsIAPgsIA3AAQAGAAAEAFQAFAFAAAFIAAA4IgrAOIArAOIAAA5QAAAFgFAFQgEAFgGgBgAABAeIAFABIAEAFIABABIACAEIACAGIAIAYIAJABIAkAAIACAAIABgBIABgHIAAgnIgFgDIgdgKIgDgBIgDgDIgCgDIgBgEIAAgBQABgEACgCQABgDAEgCIAHgDIAbgIIABgHIAAgnIgCgCIgEgBIgpAAIgDAEIgKAeIgEAGQgDADgEAAQgDAAgDgCQgEgBgBgDIgEgIIgNgdIgrABIgBAAIAAAvIACABIAfAKIACABQADABACADIABAAQABAEAAADIAAACIgCAFQgBACgDACIgCAAIgIAEIgZAIIgBAHIAAAnIABACIABABIABAAIADAAIApAAIACgEIALgeIAAgCIAEgEQADgCAEgBIABABg");
	this.shape_60.setTransform(600,75);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#B79CAA").s().p("AAPBaIgPgtIgOAtIg7AAQgGAAgFgFQgEgFAAgGIAAg2QAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAgBABAAIAngNIgsgOIAAg7QAAgGAEgFQAFgFAGAAIA6AAIAPAuIAQguIA5AAQAHAAAEAFQAFAFAAAGIAAA7IgtAOIAtAPIAAA7QAAAGgFAFQgEAFgHAAgAABAfIAGADIAEAEIABABIACAFIACAGIAIAZIAKABIAmAAIACgBIABgBIABgHIAAgpIgGgDIgegKIgDgCIgDgDIgCgDIgBgEIAAgBQAAgEACgDQACgCAEgDIAIgDIAcgJIABgHIAAgpIgCgDIgFgBIgrAAIgCAGIgLAfIgFAGQgDADgEAAQgDAAgEgCQgDgCgCgCIgDgJIgPgfIgtACIgBABIAAAxIACABIAhAKIACABQADACACADIABAAQACADAAAEIgBACIgBAGIgFADIgCABIgIAEIgbAJIgBAHIAAApIABABIABABIACABIADAAIArAAIACgEIALggIABgCIAEgEQADgCAEgBIABAAg");
	this.shape_61.setTransform(600,75);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#B79CAA").s().p("AAPBfIgPgwIgPAwIg9AAQgHAAgFgFQgFgFAAgHIAAg4QAAgDACgCIAEgDIApgOIgvgOIAAg/QAAgHAFgEQAFgGAHAAIA8AAIAQAxIARgxIA8AAQAHAAAFAGQAFAEAAAHIAAA/IgvAOIAvAQIAAA+QAAAHgFAFQgFAFgHAAgAACAhIAFACIAFAGIABABIACAEIACAHIAIAaIALABIAoAAIACAAIABgCIABgHIAAgsIgmgNIgDgCIgEgDIgCgDIgBgFIABgCQAAgDACgDQACgDAFgCIAHgDIAegJIABgIIAAgrQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAgBAAIgEgBIgtAAIgDAFIgLAhIgFAHQgEADgEAAQgEAAgDgCQgEgCgBgDIgEgJIgPggIgwABIgBABIAAA0IACABIAjALIACABQADABADAEIAAAAQACAEAAADIAAADIgCAFQgCADgDACIgCAAIgJAEIgcAJIgBAIIAAArIABACIABABIACAAIAEAAIAtAAIACgEIALghIABgDIAEgEQAEgDAEAAIACAAg");
	this.shape_62.setTransform(600,75);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#B79CAA").s().p("AAQBkIgQgzIgQAzIhAAAQgHgBgFgFQgGgFAAgHIAAg7QAAgDACgCQACgCADgCIArgOIgygQIAAhAQAAgIAGgFQAFgGAHABIBAAAIAQAyIARgyIBAAAQAHgBAGAGQAEAFAAAIIAABAIgxAQIAxARIAABBQAAAHgEAFQgGAFgHABgAACAjIAGACQADACACAEIABABIACAEIACAIIAJAbIALABIAqAAIACgBIABgBIAAg2IgFgCIgigMIgDgCIgEgDIgCgDIgBgFIABgCQAAgEACgCQACgEAFgCIAIgDIAfgKIAAg1QAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAgBAAIgEgBIgwAAIgDAFIgLAjIgGAHQgDADgFAAQgEABgEgDQgDgCgCgEIgEgJIgQghIgyABIAAACIAAA2IACABIAkALIACABQADACADADIABABQABADAAAEIAAACIgCAHQgCADgDABIgCABIgJAEIgeAJIAAA2IAAACIACAAIACABIAEAAIAvAAIACgEIAMgjIABgDIAEgEQADgDAFAAIACAAg");
	this.shape_63.setTransform(600,75);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#B79CAA").s().p("AARBoIgRg0IgQA0IhEAAQgHAAgGgFQgFgGAAgIIAAg9QAAgDACgCQABgDADgBIAtgPIgzgQIAAhFQAAgHAFgFQAGgGAHAAIBDAAIARA1IASg1IBDAAQAHAAAGAGQAFAFAAAHIAABFIg0AQIA0ASIAABDQAAAIgFAGQgGAFgHAAgAACAlIAGABQAEADABAEIABABIACAFIADAIIAJAcIA4ABIACgBIABgBIAAg5IgpgOIgEgCIgDgDIgCgEIgBgFIAAgCQAAgEACgDQADgDAFgDIAIgDIAhgKIAAg5QAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAgBIgFAAIgyAAIgDAGIgMAkQgBADgEAFQgEADgFAAQgEAAgEgDQgEgCgCgDIgEgKIgRgjIg0ABIAAABIAAA5IACABIAmAMIACABQADACADAEIABAAQACAEAAAEIgBADQAAADgCADQgCADgDABIgCABIgKAFIgfAJIAAA5IAAABIACACIACAAIAEAAIAyAAIAOgpIABgDIAFgFQADgDAFAAIACABg");
	this.shape_64.setTransform(600,75);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#B79CAA").s().p("AASBtIgSg3IgRA3IhHAAQgHgBgGgFQgGgGAAgHIAAhBQAAgDACgDQACgCADgBIAvgQIg2gRIAAhHQAAgIAGgGQAGgFAHAAIBGAAIASA3IATg3IBGAAQAHAAAGAFQAGAGAAAIIAABHIg2ARIA2ATIAABHQAAAHgGAGQgGAFgHABgAADAmIAGACQADADACAEIABABIACAGIADAIIAJAdIA7ABIACgBIABgBIAAg7IgGgDIgkgMIgFgDIgDgDIgDgDIgBgGIABgCQAAgEACgDQADgEAFgDIAJgDIAigKIAAg7IgCgDIgGgBIg0AAIgPAsQgBADgFAFQgEADgFAAQgEABgFgEQgEgCgBgDIgEgLIgSgkIg3ACIAAABIAAA7IACABIAoANIACABQAEACADADIAAABQACAEAAAEIAAADQAAADgCAEQgDADgDABIgCACIgLADIggAKIAAA8IABACIABABIACAAIAEAAIA0AAIAQgrIABgDQABgDADgCQAEgDAFAAIADAAg");
	this.shape_65.setTransform(600,75);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#B79CAA").s().p("AASBxIgSg5IgSA5IhKAAQgHAAgHgFQgFgHAAgIIAAhDQAAgDACgDQABgCADgBIAygRIg4gSIAAhKQAAgJAFgFQAHgGAHgBIBJAAIATA7IAUg7IBIAAQAJABAFAGQAGAFAAAJIAABKIg4ASIA4ATIAABKQAAAIgGAHQgFAFgJAAgAADAnQADABADACQAEADACAEIABABIACAGIADAIIAKAfIA9ABIACgBIABgCIAAg9IgHgDIglgMIgFgDIgEgEIgCgDIgBgHIAAgBQABgFACgDQADgEAFgDIAJgDIAkgLIAAg9IgDgEIgFAAIg2AAIgDAHIgOAnQgBADgFAFQgEAEgFAAQgFAAgEgEQgEgCgCgDIgEgMIgTglIg4ABIgBACIAAA9IACABIAqAOIACABQAEACADAEIABABQACAEAAAEIgBADQAAAEgCADQgCADgEACIgDABIgKAEIgiALIAAA+IABABIABABIADAAIAEABIA2AAIAQgtIABgDQACgDADgCQAEgEAFAAIADAAg");
	this.shape_66.setTransform(600,75);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#B79CAA").s().p("AATB2IgTg8IgTA8IhMAAQgIAAgHgGQgGgHAAgIIAAhGQAAgDACgDQACgDADgBIAzgRIg6gSIAAhOQAAgIAGgHQAHgGAIAAIBLAAIAUA8IAVg8IBLAAQAJAAAGAGQAGAHAAAIIAABOIg7ASIA7AUIAABNQAAAIgGAHQgGAGgJAAgAADApIAHADQAEADACAEIABACIACAFIADAJIAKAgIBAABIACgBIABgCIAAhAIgugQIgFgDIgEgEIgCgDIgCgHIABgBQAAgFADgDQADgEAFgDIAKgDIAlgMIAAhBIgDgCIgGgBIg4AAIgDAHIgOApQgBAEgFAFQgFADgFAAQgFABgFgEQgEgDgCgEIgEgLIgTgnIg7ACIgBABIAABAIADABIArAPIACAAQAEADADADIABABQACAFAAAEIAAADIgDAHQgCAEgEACIgDABIgLAEIgiALIgBBBIABACIACABIACAAIAEAAIA5AAIAQgvIACgEQABgDAEgCQAEgEAFAAIADABg");
	this.shape_67.setTransform(600,75);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#B79CAA").s().p("AAUB6IgUg9IgTA9IhQAAQgIAAgHgFQgGgIAAgIIAAhJQAAgDACgDIAFgEIA1gSIg8gTIAAhQQAAgJAGgHQAHgGAIgBIBPAAIAUA/IAWg/IBOAAQAJABAGAGQAGAHAAAJIAABQIg9ATIA9AUIAABRQAAAIgGAIQgGAFgJAAgAADArIAIADQAEADABAEIABACIADAGIADAJIAKAhIBDAAIACAAIABgCIAAhCIgwgRIgFgCIgEgFIgDgDIgBgIIAAgBQABgGADgDQADgEAGgDIAKgEIAmgMIAAhCQAAAAAAgBQAAAAgBgBQAAAAgBgBQAAAAgBgBIhBAAIgDAHIgOArQgCAEgFAFQgFAEgGgBQgEABgFgEQgEgDgCgEIgFgLIgUgpIg9ACIgBACIAABCIAwAQIACABQAEACADAEIABABQADAEAAAFIgBADQAAAEgDADQgCAFgEACIgDABIgLAEIgkAMIgBBCIABACIACABIADAAIAEAAIA7AAIARgwIABgDIAFgGQAFgDAFAAIADAAg");
	this.shape_68.setTransform(600,75);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#B79CAA").s().p("AAVB/IgVg/IgUA/IhTAAQgJAAgHgGQgGgHAAgJIAAhLQAAgEACgDQACgDADgBIA4gTIg/gUIAAhTQAAgKAGgGQAHgHAJAAIBSAAIAVBBIAXhBIBRAAQAJAAAHAHQAGAGAAAKIAABTIg/AUIA/AWIAABTQAAAJgGAHQgHAGgJAAgAAEAtQADAAAEADQAEADACAFIABABIADAHIACAJIAMAjIBEAAIADgBIABgCIAAhFIgygSIgFgCIgFgEIgCgEIgBgIIAAgCQAAgFADgDQADgFAHgCIAKgEIAogNIAAhFQAAAAAAgBQgBAAAAAAQAAgBgBAAQgBgBAAAAIhEAAIgDAHIgPAsQgBAEgFAGQgGADgGAAQgFAAgFgDQgEgDgCgEIgFgNIgVgpIg/ABIgBACIAABFIAyARIACAAQAEACAEAFIABAAQACAFAAAFIgBAEQAAAEgCADQgDAFgEABIgDABIgMAFIglAMIgBBGIABACIACABIADAAIAFAAIA9AAIARgzIABgDIAGgGQAFgEAFAAIAEABg");
	this.shape_69.setTransform(600,75);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#B79CAA").s().p("AAVCEIgVhDIgVBDIhVAAQgKAAgHgHQgHgHAAgJIAAhPQAAgDADgEQACgDADgBIA6gTIhCgVIAAhWQAAgKAHgHQAHgHAKAAIBUAAIAWBEIAXhEIBUAAQAKAAAHAHQAHAHAAAKIAABWIhCAVIBCAWIAABXQAAAJgHAHQgHAHgKAAgAAEAuIAIADQAEAEACAEIABACIACAHIADAJIAMAkIBHAAIADgBIABgBIAAhIIg0gSIgGgCIgEgGIgCgDQgCgEAAgEIABgCQAAgFADgEQADgEAHgDIALgEIApgNIAAhIQAAAAAAgBQgBAAAAgBQgBAAAAgBQgBAAgBgBIhGAAIgSA2QgBAEgGAFQgFAFgHAAQgFAAgFgFQgFgCgCgEIgEgOIgWgrIhCADIAAABIAABIIAzARIACABQAFACADAEIABABQACAEAAAGIAAAEQgBAEgCADQgDAFgEACIgDABIgNAEIgmANIAABJIABABIABABIADAAIAFAAIA/AAIASg0IACgEQACgDAEgDQAEgDAGAAIAEAAg");
	this.shape_70.setTransform(600,75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_47,p:{scaleX:0.01,scaleY:0.01}}]},47).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_47,p:{scaleX:0.052,scaleY:0.052}}]},1).to({state:[{t:this.shape_47,p:{scaleX:0.052,scaleY:0.052}}]},24).wait(20));

	// Layer 2
	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#B79CAA").s().p("EgHnCXfQjzhhi5i6Mgv5gv5QiRiQggjKQgijKBbi3MAXdgvaMg1gAa5Mg08g07Qi6i6hhjzQhfjpAAj+QAAj9BfjqQBhjzC6i5MA0Eg0EMA3XAavMgavg3XMA0Eg0EQC5i6DzhhQDqhfD9AAQD+AADpBfQDzBhC6C6MA07A08MgbKA1xMA2Dga4MA08A07QC5C5BiDzQBfDqAAD9QAAD+hfDpQhiDzi5C6Mg1EA1EMg17gbTMAbCA2LMg0zA00Qi6C6jzBhQjpBfj+AAQj9AAjqhfgEgmPAikQBJAeA5A4QBcBbAVCAQAWB+g6B0MgXeAvaQgiBEANBLQAMBKA1A2MAv6Av5QB+B+CjBEQCkBDCzAAQCzAACkhDQCjhEB/h+MAxngxoMgZCgyKQg6hzAWiAQAViABchbQA4g5BLgeQBIgeBPAAQBfAABVArMAx6AZRMAx2gx3QB+h/BEijQBDikAAizQAAizhDikQhEijh+h+MgxwgxwMgyCAY5QhUApheAAQhQAAhIgeQhMgeg4g6QhbhbgUiAQgVh/A6h0MAZJgxwMgxvgxuQh/h+ijhEQikhDizAAQizAAikBDQijBEh+B+Mgw8Aw8MAY0AzXQA4BygVB+QgWB+hZBbQg6A5hKAdQhJAehPABQhcAAhRgpMgzXgYzMgw8Aw7Qh+B+hECjQhDCkAACzQAACzBDCkQBECjB+B/MAxvAxvMAxfgY4QBUgqBfAAQBPAABJAeg");
	this.shape_71.setTransform(600,75,0.013,0.013);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#B79CAA").s().p("AgGCRIgGgDIgugvQgDgBAAgDQgBgEACgDIAWguIg0AaIgygyQgDgDgBgDQgCgEABgEIABgGQABgDADgEIAygxIA1AaIgag2IAzgyQADgDADgBIAGgBQAEAAAEABQADABADADIAyAzIgaA0IA0gaIAzAyQADAEABADIABAGQAAAEgBAEQgBADgDADIgzAyIg0gaIAaA1IgyAzIgGADIgIABIgGgBgAgkAiIACABIACADIgBADIgWAwQAAAAAAABQAAAAAAAAQAAAAAAABQABAAAAAAIAtAuQACACADAAIAEACQADAAADgCIADgCIAwgwIgYgwIAAgDIABgDIACgCIACAAIADABIAwAXIAwgvIADgFQABgCAAgDIgBgEIgDgEIgwgwIgwAXIgDABIgCAAIgCgBIgBgDIAAgEIAYgwIgwgwIgDgDQgDgBgDAAIgEABIgFADIguAvIAYAxQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABIgCADIgCABIgCABIgCgBIgygXIgxAzIgBAEIABAFIACAFIAwAvIAwgXIACgBIACABg");
	this.shape_72.setTransform(600,75);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#B79CAA").s().p("AgHCnIgIgEIg0g2QgDgCgBgEQAAgDACgDIAZg0Ig6AdIg7g6QgDgDgBgEQgCgFgBgEQABgDACgEQABgFADgDIA6g5IA8AeIgdg+IA5g5QADgDAFgCQAEgCADAAQAFAAADACQAFACADADIA6A6IgeA8IA8geIA6A6QADADACAFQACAEAAADQAAAEgCAFQgCAEgDADIg6A6Ig8gdIAeA7Ig6A7QgDACgFACQgDACgFAAIgHgCgAgpAmIACABIACAFIAAAEIgbA2IABACIA1A1IAFAEIAFABIAGgBQADgBACgDIA2g3Igbg3IgBgEIACgEIADgBIACAAIADAAIA4AcIA2g3IADgFIABgGIgBgFIgDgFIg2g2Ig4AbQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgCgBIgDgBIgCgEIABgEIAbg4Ig2g2IgFgDIgGgBIgFABIgFADIg2A2IAcA5IAAADIgBAFIgDABIgDABIgDgBIg4gbIg6A6IAAAFIAAAGIAEAFIA3A3IA2gcIADAAIADAAg");
	this.shape_73.setTransform(600,75);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#B79CAA").s().p("AgJC9QgEgCgEgEIg7g7QgDgDgBgEQgBgFACgDIAeg7IhDAhIhBhBQgEgDgCgFQgCgFAAgFQAAgEACgEQACgFAEgDIBAhBIBFAhIgihFIBBhAQAEgEAEgCQAFgCAEAAQAFAAAFACQAEACADAEIBCBBIghBDIBDghIBBBCQAEADACAFQACAEAAAEQAAAFgCAFQgCAFgEADIhBBCIhDgiIAhBDIhCBCQgDAEgEACIgKABIgJgBgAguArIACACIACAEIgBAFIgdA+QAAAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIA8A8QACACADABIAGABIAHgBQADgBACgCIA+g+Igfg+IgBgGIACgDIADgCIADAAIADAAIA+AfIA/g+IADgFIABgHIgBgGIgDgFIg/g+Ig+AfIgDABIgDgBIgDgBQgCgCAAgDIABgEIAfg+Ig+g/IgFgDIgHgBIgGABIgFADIg9A+IAfA/QAAABAAABQABAAAAABQAAAAAAABQAAAAAAABIgDAFIgDABIgCABIgEgBIhAgfIhABCIgBAGIABAHIADAFIA+A+IA+geIAEgBIADAAg");
	this.shape_74.setTransform(600,75);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#B79CAA").s().p("AgJDSQgFgCgFgEIhChDQgDgDgBgEQAAgFABgDIAhhCIhKAlIhJhJQgFgEgBgFQgDgFAAgGQAAgEADgFQABgGAFgDIBIhIIBMAlIglhOIBIhIQAFgDAFgCQAEgDAFAAQAGAAAFADQAFACADADIBLBJIgmBLIBLglIBJBKQAEADABAGQADAFAAAEQAAAGgDAFQgBAFgEAEIhJBJIhLglIAlBKIhKBKQgDAEgFACQgFACgGAAQgFAAgEgCgAg0AwIADACQACABABAEIgBAFIgiBEQAAABABAAQAAABAAAAQAAABAAAAQABAAAAAAIBDBDQACADADABIAHABQAEAAAEgBQADgBADgDIBEhFIgjhGIAAgEQAAgDADgCIADgDIADAAIAEABIBFAjIBEhGQADgCACgDQABgEABgEIgCgGQgCgEgDgDIhEhEIhFAiIgEABIgDAAIgDgDQgDgCAAgCIAAgGIAjhFIhEhEIgGgFQgEgBgEgBIgHACIgFAFIhFBDIAjBHIAAAGQAAACgBACIgEADIgDAAIgDgBIhHgiIhJBKIgBAGIABAIIAEAFIBFBGIBFgjIAEgBIADABg");
	this.shape_75.setTransform(600,75);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#B79CAA").s().p("AgKDoQgGgDgEgEIhJhJQgFgEAAgEQgBgGACgDIAkhJIhSApIhRhRQgEgFgCgFQgDgGAAgGQAAgFADgFQACgGAEgFIBQhPIBUApIgohVIBQhPQAEgFAGgCQAFgDAFABQAHgBAFADQAFACAFAFIBRBQIgqBSIBTgpIBQBRQAFAFACAGQACAFAAAFQAAAGgCAGQgCAFgFAFIhQBRIhTgpIAqBSIhRBRQgFAEgFADQgFACgHAAQgFAAgFgCgAg5A1IADACQACACAAAEQABACgCADIgkBMIACADIBJBJQADADAEACIAHABQAFAAADgBQAEgCADgDIBMhMIgmhNIgBgFIACgFQABgBAAAAQABAAAAgBQABAAAAAAQAAAAABAAIADgBIAEABIBNAnIBMhNQADgDACgDQABgFAAgEIgBgHQgCgEgDgDIhMhMIhNAmIgEABIgDgBIgEgBIgCgGIABgFIAmhNIhMhMIgHgFQgDgBgFAAIgHABIgHAFIhLBLIAmBPQACACgBADQgBADgCADIgDABIgEABIgEgBIhOglIhQBRIgBAHQAAAEABAFIAFAGIBMBNIBMgnIAEgBIAEABg");
	this.shape_76.setTransform(600,75);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#B79CAA").s().p("AgLD9QgHgDgFgEIhPhRQgFgDgBgFQAAgGACgFIAohPIhaAtIhYhYQgFgFgDgGQgCgGAAgHQAAgFACgHQACgGAGgFIBXhWIBcAsIgshdIBWhWQAFgGAHgBQAFgDAGgBQAHABAGADQAHABAEAGIBZBYIguBZIBbgtIBXBZQAGAFACAGQADAHAAAFQAAAHgDAGQgCAGgGAFIhYBYIhagtIAuBaIhZBZQgEAEgHADQgGADgHgBQgGABgFgDgAg/A6IADACQADACABAEQAAADgBAEIgoBSQAAABAAAAQAAAAAAABQABAAAAABQAAAAAAAAIBQBQQAEAEAEACIAIABQAFAAAEgBQAFgCACgEIBThTIgphTQgCgDAAgEQABgDADgCQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAgBIAEAAIAEABIBUAqIBThTQADgEACgEQACgEAAgFQAAgEgCgDQgCgFgDgEIhThSIhUApQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAIgEgCIgDgCQgDgCgBgDQAAgEACgDIAphTIhThTQgCgEgFgBQgEgCgFAAQgEAAgEACQgEABgEAEIhRBRIAqBWQABADgBAEQgBADgBACIgEADIgEABIgFgBIhVgqIhXBaQgBADgBAEQABAFABAEQACAEADAEIBTBTIBSgqIAGgBIADABg");
	this.shape_77.setTransform(600,75);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#B79CAA").s().p("AgMESQgIgCgFgGIhWhWQgFgEgBgGQAAgGACgFIAqhWIhhAxIhfhgQgGgFgCgHQgDgHAAgHQAAgGADgHQACgHAGgFIBeheIBkAxIgwhlIBeheQAFgGAIgCQAGgDAGAAQAHAAAHADQAHACAFAGIBgBgIgxBhIBhgxIBhBgQAFAFADAHQACAHAAAGQAAAHgCAHQgDAHgFAFIhhBgIhhgxIAxBiIhgBfQgFAGgHACQgHADgHAAQgGAAgGgDgAhEA/IAEACQACACABAFIgCAHIgrBZQAAABABAAQAAABAAAAQAAABABAAQAAABABAAIBWBXQADAEAFABQAFACAEAAQAFAAAFgCQAEgBAEgEIBahaIguhbQgBgEAAgDQABgDACgDIAFgDIAEAAIAFABIBbAuIBahbQADgDACgFQACgFAAgFQAAgEgCgEQgCgGgDgCIhahbIhbAtIgFABIgEAAIgFgDQgCgCgBgEQAAgEABgDIAuhbIhahaQgEgDgEgCQgFgCgFAAQgEAAgFACQgFACgDADIhZBZIAtBdQACAEgBADQAAAEgDADIgDACIgFABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBIhegtIheBiQgBAEAAAEIABAKQACAFADADIBaBbIBaguIAFgBIAFABg");
	this.shape_78.setTransform(600,75);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#B79CAA").s().p("AgNEoQgIgDgGgGIhdhdQgFgFgBgGQgBgGADgGIAuhcIhpA0IhnhnQgGgGgDgHQgDgHAAgIQAAgHADgHQADgHAGgGIBmhmIBsA1Ig0htIBlhlQAGgGAIgDQAGgDAHAAQAIAAAHADQAHADAGAGIBoBnIg1BpIBpg1IBnBoQAGAGADAHQADAHAAAHQAAAIgDAHQgDAHgGAGIhnBnIhpg1IA1BqIhoBnQgGAGgHADQgHADgIAAQgHAAgGgDgAhJBEIADACQADADABAEQAAAEgBADIgvBhQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIBdBeQAEAEAFABQAEADAFAAQAFAAAFgDQAGgBADgEIBhhiIgwhhQgCgEAAgEQABgEADgCIAEgDIAFgBIAFABIBhAyIBihiQAEgEACgFQACgFAAgFQAAgFgCgEQgCgGgEgDIhihiIhhAxQgDABgCAAIgFgBIgEgCQgDgDgBgEQAAgEACgDIAwhiIhhhhQgDgEgGgCQgFgCgFAAQgFAAgEACQgFACgEAEIhgBgIAxBkQABAEAAADQgBAEgCADIgFADIgEABIgGgBIhkgxIhlBpQgDAEAAAFQAAAFADAFQACAFADAEIBhBiIBigxIAFgBIAFABg");
	this.shape_79.setTransform(600,75);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#B79CAA").s().p("AgPE9QgIgCgGgHIhkhkQgFgFgBgGQgBgHADgGIAxhkIhxA5IhuhvQgGgGgDgHQgDgJAAgIQAAgHADgIQADgIAGgFIBthuIB0A5Ig4h1IBthtQAGgGAIgDQAIgDAHgBQAIABAIADQAIADAGAGIBvBvIg4BwIBwg4IBvBwQAGAFADAIQAEAIAAAHQAAAIgEAJQgDAHgGAGIhvBwIhwg6IA4ByIhvBuQgGAHgIACQgIADgIAAQgHAAgIgDgAhPBJIAFACQACADABAFQABAEgDAEIgxBnQAAABAAABQAAAAAAABQABAAAAABQAAAAABABIBlBkQADAFAGACQAFABAFABQAGgBAFgBQAGgCADgFIBphoIg1hpQgCgEABgEQABgEADgDIAFgDIAFgBIAFACIBpA1IBohqQAEgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEIhohpIhpA1IgFABIgGgBIgEgDQgDgDgBgEQgBgEACgEIA1hpIhphoQgDgEgGgCQgFgCgGAAQgFAAgFACQgGACgDAEIhnBnIA0BsQACADgBAEQgBAEgDAEIgEACIgFABQgDABgDgCIhrg0IhuBwQgCAGAAAEQAAAGACAFQADAFAEAEIBoBqIBog1QADgCADABIAFABg");
	this.shape_80.setTransform(600,75);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#B79CAA").s().p("AgQFTQgIgDgHgHIhrhrQgFgFgBgHQgBgHADgHIA0hqIh3A8Ih3h2QgGgGgDgJQgFgIAAgJQAAgIAFgIQADgJAGgGIB1h1IB7A8Ig7h8IB0h0QAHgHAIgDQAIgDAIAAQAJAAAIADQAJADAGAHIB3B2Ig9B5IB5g9IB2B3QAHAGADAJQAEAIgBAIQABAJgEAIQgDAJgHAGIh2B3Ih5g9IA9B5Ih3B2QgGAHgJADQgIADgJAAQgIAAgIgDgAhUBNIAEADQADADABAFQABAEgDAFIg0BuQAAADACACIBrBrQAFAFAFACQAGACAFAAQAHAAAFgCQAGgCAEgFIBvhvIg4hwQgCgEABgFQAAgEAEgDIAFgDIAFgBIAGABIBwA5IBwhwQAEgEACgGQADgGAAgGQAAgFgDgGQgCgGgEgEIhwhwIhwA4IgGACIgFgBIgFgDQgEgEAAgEQgBgFACgEIA4hvIhvhvQgEgFgGgCQgFgDgHAAQgFAAgGADQgFACgFAFIhtBtIA3BzQACAEgBAEQAAAFgEADIgEADIgGABQgDAAgCgBIhzg4Ih1B4QgCAGAAAFQAAAGACAGQADAGAEAEIBvBwIBvg4QADgCADAAIAGABg");
	this.shape_81.setTransform(600,75);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#B79CAA").s().p("AgRFpQgJgEgHgGIhyhzQgFgFgCgHQgBgIAEgHIA3hxIh/BAIh+h+QgHgGgDgJQgEgKAAgJQAAgIAEgJQADgJAHgHIB8h8ICEBAIhAiEIB8h8QAHgHAJgDQAJgEAIAAQAJAAAJAEQAKADAGAHIB+B+IhACAICAhAIB+B+QAHAHADAJQAEAJAAAIQAAAJgEAKQgDAJgHAGIh+B/IiAhCIBACCIh+B+QgGAGgKAEQgJADgJAAQgIAAgJgDgAhaBTIAFACQADAEABAFQABAEgCAFIg5B2QABADACACIByByQAEAFAHACQAFADAGAAQAHAAAGgDQAGgCAFgFIB2h3Ig8h3QgCgEAAgFQABgFAEgDIAFgDIAGgBQADAAADACIB3A8IB3h4QAEgEADgGQACgGABgHQgBgFgCgHQgDgFgEgGIh2h2Ih4A8QgDABgDAAIgGgBIgFgDQgEgEgBgFQAAgEACgFIA8h2Ih2h3QgFgEgGgDQgGgCgHAAQgGAAgFACQgHADgEAEIh1B1IA7B7QACAEgBAEQgBAFgCAEIgGADIgFABQgEAAgCgBIh7g8Ih7B/QgDAHAAAFQAAAHADAGQACAGAEAEIB3B4IB2g8QACgCAEABIAGABg");
	this.shape_82.setTransform(600,75);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#B79CAA").s().p("AgSF+QgKgEgHgHIh4h5QgGgGgCgIQgBgIADgHIA8h3IiHBEIiFiGQgIgHgEgKQgEgJAAgKQAAgJAEgJQAEgKAIgHICDiDICLBDIhDiMICDiDQAHgHAKgEQAJgEAJAAQAKAAAJAEQAKAEAHAHICGCFIhFCIICJhEICFCGQAHAHAEAKQAEAJAAAJQAAAKgEAJQgEAKgHAHIiFCGIiJhFIBFCJIiGCFQgHAHgKAEQgJAEgKAAQgJAAgJgEgAhfBXIAFAEQADADACAFQAAAFgCAFIg8B9QAAADADACIB4B5QAFAFAHACQAGADAGAAQAHAAAHgDQAGgCAFgFIB9h+Ig/h+QgCgFABgEQAAgGAEgDQADgDADgBIAFgBIAHACIB+BAIB+h+QAFgFADgHQACgGAAgHQAAgGgCgGQgDgHgFgFIh+h9Ih+A+QgDACgEAAIgGgBIgFgEQgEgDAAgFQgBgFACgFIBAh+Ih+h9QgFgFgGgDQgHgCgHAAQgGAAgGACQgHADgFAFIh7B8IA/CBQACAFgBAFQgBAEgEAEIgFAEIgGABIgHgCIiBg+IiECHQgCAGAAAGQAAAHACAGQAEAHAEAFIB9B9IB9g/QAEgBAEAAIAGABg");
	this.shape_83.setTransform(600,75);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#B79CAA").s().p("AgTGUQgKgFgIgHIh/iAQgGgFgCgJQgCgJAEgHIA/h+IiPBIIiMiOQgIgHgFgLQgDgJAAgLQAAgJADgKQAFgKAIgIICKiLICTBIIhGiUICKiLQAIgHAKgFQAJgDAKAAQALAAAJADQAKAFAIAHICNCNIhICQICQhIICNCNQAIAIADAKQAEAKAAAJQAAALgEAJQgDALgIAHIiNCOIiQhJIBICRIiNCMQgIAHgKAFQgJADgLAAQgKAAgJgDgAhkBcQACACADACQADAEABAFQABAFgCAFIg/CEQAAAEACACICAB/QAFAGAHACQAHADAGAAQAHAAAIgDQAGgCAFgGICFiEIhDiFQgCgFAAgGQACgFADgEQACgDAEAAIAGgBQAEgBAEACICFBEICEiFQAFgGADgHQADgGAAgIQAAgHgDgGQgDgHgFgFIiEiFIiFBDQgEACgEAAIgHgCQgDgBgCgDQgDgDgCgGQAAgFACgFIBDiFIiFiEQgFgFgGgDQgIgDgHAAQgGAAgHADQgHADgFAFIiCCCIBCCJQACAFgBAFQgBAGgDADIgGAEQgDABgEABIgHgCIiJhDIiKCPQgDAGAAAHQAAAIADAGQADAHAFAGICFCEICDhDQAEgBAEAAQAEAAADABg");
	this.shape_84.setTransform(600,75);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#B79CAA").s().p("AgUGpQgLgEgIgIIiGiHQgHgGgBgJQgCgJAEgIIBDiFIiXBMIiViVQgIgIgEgLQgFgKAAgLQAAgKAFgKQAEgLAIgIICTiSICbBLIhLicICSiSQAIgIALgEQAKgEAKAAQALAAALAEQAKAEAIAIICVCVIhMCXICYhMICUCVQAIAIAEALQAEAKABAKQgBALgEAKQgEALgIAIIiVCVIiXhNIBLCZIiUCUQgIAIgKAEQgLAEgLAAQgKAAgKgEgAhqBhQADABADADQADAEABAFQACAGgDAFIhDCLQAAAEADACICGCGQAGAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGICLiLIhGiNQgDgFABgFQABgGAEgEQACgDAEgBIAHgBQAEAAAEACICLBHICNiMQAFgGADgHQADgHAAgIQAAgHgDgHQgDgHgFgGIiMiLIiMBFQgEACgEAAIgHgBQgEgBgCgDQgEgEgBgFQgBgGADgFIBHiMIiMiLQgGgGgHgDQgHgDgIAAQgHAAgHADQgHADgGAGIiJCJIBGCQQACAFgBAGQgBAFgEAEIgFAEQgEABgDAAIgIgBIiQhGIiRCWQgDAHgBAHQABAIADAHQADAHAFAGICLCLICMhGQADgBAFAAQADAAADABg");
	this.shape_85.setTransform(600,75);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#B79CAA").s().p("AgVG/QgLgEgJgJIiNiOQgHgGgBgJQgCgJAEgJIBGiMIifBQIicicQgIgJgEgLQgFgLAAgMQAAgLAFgLQAEgKAIgJICaiaICjBQIhPikICaiZQAJgJALgFQAKgEALAAQAMAAALAEQALAFAIAJICcCbIhQCfICghPICbCcQAJAJAFAKQAEALAAALQAAAMgEALQgFALgJAJIibCcIighRIBQCgIicCcQgIAJgLAEQgLAEgMAAQgLAAgKgEgAhvBmIAFAEQAFAEABAHQAAAFgCAGIhGCRQAAAEACADICOCNQAGAGAHADQAIACAHABQAIgBAIgCQAHgDAGgGICTiTIhLiTQgCgGABgFQABgHAFgDQACgEAEgBIAGgBQAFAAADACICUBKICTiTQAFgFAEgIQADgHgBgJQABgHgDgIQgEgHgFgGIiSiTIiVBKQgDACgFAAIgHgBIgFgFQgFgEgBgGQgBgGACgFIBLiTIiTiTQgGgFgHgEQgIgCgIAAQgHAAgIACQgHAEgGAFIiQCRIBJCXQACAGgBAFQgBAGgDAEIgHAFIgHABQgEAAgEgCIiXhJIiaCdQgDAIAAAHQAAAJADAHQAEAIAFAFICTCTICShKQAEgCAFAAIAHACg");
	this.shape_86.setTransform(600,75);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#B79CAA").s().p("AgWHUQgMgFgJgIIiUiVQgHgHgCgJQgBgKAEgJIBJiSIimBTIijikQgKgJgEgLQgFgMAAgMQAAgLAFgMQAEgLAKgJIChihICrBTIhTisIChihQAJgJAMgEQALgFALAAQAMAAAMAFQALAEAJAJICkCkIhUCmICohTICjCkQAIAJAFALQAFAMAAALQAAAMgFAMQgFALgIAJIikCkIinhUIBTCnIijCkQgJAIgLAFQgMAFgMAAQgLAAgLgFgAh1BrIAHAEQADAEABAHQACAGgDAFIhKCaQABADACADICVCUQAGAGAHADQAIADAIAAQAJAAAHgDQAJgDAGgGICZiaIhOibQgCgFABgGQABgHAEgEQADgDAEgBIAHgBQAFAAAEACICaBOICaibQAGgGADgIQADgHABgJQgBgIgDgHQgDgIgGgHIiaiZIiaBNQgEACgFAAIgIgCIgGgEQgEgFgBgGQgBgGACgFIBPiaIiaiaQgGgGgJgDQgHgDgJAAQgIAAgIADQgHADgGAGIiYCXIBOCfQACAGgBAGQgCAGgEAEIgGAEIgHACIgJgCIifhNIigCmQgEAHABAIQgBAJAEAHQAEAIAFAGICaCaICZhNQAEgCAFAAIAHACg");
	this.shape_87.setTransform(600,75);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#B79CAA").s().p("AgYHqQgLgFgKgKIibiaQgHgIgCgKQgCgKAFgJIBMiaIiuBXIiqirQgKgJgEgMQgGgMAAgNQAAgMAGgMQAEgMAKgJICoipICzBXIhXizICpioQAKgKALgFQAMgEAMAAQANAAAMAEQAMAFAJAKICrCqIhXCvICvhXICqCrQAKAJAFAMQAEAMAAAMQAAANgEAMQgFAMgKAJIiqCsIivhYIBXCvIirCqQgJAKgMAFQgMAEgNAAQgMAAgMgEgAh7BwIAHAEQAEAEACAHQABAHgDAFIhNChQABAEACACICcCbQAFAGAJAEQAIADAIAAQAJAAAIgDQAJgEAGgGIChihIhRihQgDgGAAgHQACgGAEgFQADgDAFgBQADgCAEAAQAEAAAFACICiBSICgihQAHgHADgIQADgIABgJQgBgIgDgIQgDgJgHgGIigihIiiBRQgFACgEAAIgIgCQgEgBgDgDQgEgFgCgGQAAgHADgFIBRiiIihigQgGgGgJgEQgIgDgJAAQgIAAgIADQgJAEgFAGIifCeIBQCmQADAGgBAGQgBAGgEAFIgHAFQgEABgEAAQgEAAgFgCIilhQIipCtQgEAIAAAIQAAAJAEAIQAEAIAGAHIChChICghRQAEgCAFAAQAEAAADACg");
	this.shape_88.setTransform(600,75);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#B79CAA").s().p("AgZH/QgNgFgJgKIiiihQgHgIgCgLQgCgKAFgKIBPigIi0BbIizizQgKgJgFgNQgGgNABgNQgBgMAGgNQAFgNAKgJICwiwIC6BaIhai7ICwivQAJgKANgFQANgFAMAAQAOAAAMAFQANAFAKAKICyCyIhcC2IC3hbICyCzQALAJAEANQAFANABAMQgBANgFANQgEANgLAJIizCzIi2hcIBcC3IiyCyQgKAKgNAFQgMAFgOAAQgMAAgNgFgAiAB1QAEABADADQAEAFACAHQABAGgDAHIhRCnQABAEADADICiChQAGAHAJAEQAIADAJAAQAJAAAJgDQAJgEAHgHICninIhVipQgCgGABgHQAAgHAGgFQADgDADgBIAIgCQAFAAAFACICoBWICpipQAGgGAEgJQAEgJgBgJQABgJgEgIQgEgJgGgGIioioIipBUQgFACgFAAIgIgCQgDgBgDgDQgGgFAAgHQgBgHACgGIBWioIioinQgHgHgJgEQgJgDgJAAQgJAAgIADQgJAEgGAHIimClIBUCtQAEAGgCAHQgBAGgFAFIgHAFIgIABQgFAAgEgCIithUIivC1QgEAIAAAJQAAAJAEAJQADAJAHAGICnCoICohUQAEgCAFAAQAEAAAEACg");
	this.shape_89.setTransform(600,75);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#B79CAA").s().p("AgaIVQgNgGgKgKIioioQgJgIgBgLQgDgLAGgLIBSimIi8BeIi6i6QgLgKgFgNQgFgNAAgOQAAgNAFgNQAFgNALgKIC3i4IDDBfIhfjDIC4i3QAKgLANgFQAOgFAMAAQAOAAANAFQAOAFAKALIC5C6IhfC9IC+hfIC7C7QAJAKAGANQAFANAAANQAAAOgFANQgGANgJAKIi7C7Ii+hgIBfC/Ii5C5QgKAKgOAGQgNAFgOAAQgMAAgOgFgAiGB6QAEABAEADQAEAFACAHQABAHgDAHIhUCuQABAEADADICoCpQAHAHAJADQAJAEAJAAQAKAAAJgEQAJgDAHgHICuivIhXiwQgEgHABgHQACgHAEgFQADgDAFgBIAIgCQAGAAAEACICvBZICwivQAHgHADgJQAEgJAAgKQAAgJgEgJQgDgJgHgHIivivIiwBYQgEACgGAAQgEAAgEgCQgEgBgEgDQgEgGgCgGQgBgIAEgGIBYivIivivQgHgHgJgDQgJgEgKAAQgJAAgJAEQgJADgHAHIisCsIBYC1QADAGgCAHQgBAHgFAFQgDADgEACQgEACgEAAQgFAAgFgCIi0hYIi3C8QgEAJAAAJQAAAKAEAJQAEAJAGAHICwCvICthYQAFgCAFAAQAFAAADACg");
	this.shape_90.setTransform(600,75);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#B79CAA").s().p("AgbIqQgOgFgLgLIiuivQgJgJgCgLQgCgLAGgLIBWitIjEBiIjCjCQgKgKgGgOQgGgNAAgPQAAgOAGgNQAGgOAKgKIC/i/IDKBiIhijLIC+i+QALgLAOgFQAOgGANAAQAPAAANAGQAOAFALALIDCDBIhkDFIDGhiIDBDCQALAKAGAOQAFANAAAOQAAAPgFANQgGAOgLAKIjCDCIjFhjIBjDGIjBDBQgLALgOAFQgNAGgPAAQgNAAgOgGgAiKB/QAEABADADQAFAFABAIQACAHgEAHIhXC1QAAAFAEADICvCvQAHAHAJAEQAKAEAJAAQAKAAAJgEQAKgEAHgHIC2i2Ihci3QgDgHABgHQACgIAFgEQADgEAFgBQAEgCAEAAQAFAAAFACIC3BdIC2i3QAHgHAEgKQAEgJAAgKQAAgKgEgIQgEgKgHgHIi2i2Ii3BbQgFACgFAAQgFAAgEgCQgEgBgDgDQgFgGgCgHQgBgIADgGIBci2Ii2i2QgHgHgKgEQgJgEgKAAQgJAAgKAEQgJAEgHAHIizCzIBbC8QADAHgBAHQgCAHgEAFIgIAFQgEACgFAAQgFAAgFgCIi8hbIi+DEQgEAIAAAKQAAAKAEAJQAEAKAHAHIC2C2IC2hbQAEgCAGAAQAEAAAFACg");
	this.shape_91.setTransform(600,75);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#B79CAA").s().p("AgcJAQgOgGgMgLIi1i2QgJgJgCgMQgCgMAFgLIBai0IjMBnIjJjKQgLgLgGgOQgFgOAAgPQAAgOAFgOQAGgOALgLIDGjGIDSBmIhljTIDFjGQAMgLAOgGQAOgFAOAAQAPAAAOAFQAOAGALALIDKDJIhoDNIDOhnIDJDKQALALAGAOQAFAOABAOQgBAPgFAOQgGAOgLALIjJDKIjOhoIBoDOIjKDJQgLALgOAGQgOAFgPAAQgOAAgOgFgAiQCDIAIAGQAFAFACAIQAAAHgDAHIhbC8QABAFAEADIC2C2QAHAIAKAEQAJAEAKAAQAKAAAKgEQAKgEAHgIIC9i9Ihfi+QgDgHABgHQABgIAGgFQADgEAFgCQAEgBAEAAQAGAAAFACIC+BgIC9i+QAIgHAEgKQAEgKAAgKQAAgKgEgJQgEgKgIgHIi9i+Ii+BfQgFACgGAAIgJgBQgEgCgDgEQgGgFgBgIQgBgHADgHIBgi9Ii+i9QgHgIgKgEQgKgEgKAAQgKAAgJAEQgKAEgHAIIi7C6IBfDDQAEAHgCAHQgCAIgFAFIgIAFQgDACgGAAQgFAAgFgCIjDhfIjFDMQgFAJAAAKQAAAKAFAKQAEAKAHAHIC9C+IC9hfQAEgCAGAAIAJABg");
	this.shape_92.setTransform(600,75);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#B79CAA").s().p("AgdJVQgPgGgLgLIi9i9QgJgJgCgNQgCgMAFgLIBdi7IjTBqIjQjRQgMgLgGgPQgGgOgBgQQABgPAGgOQAGgPAMgLIDNjOIDaBqIhqjbIDOjNQALgLAPgGQAPgGAOAAQAQAAAPAGQAPAGAKALIDSDRIhrDUIDUhqIDRDRQALALAHAPQAFAOAAAPQAAAQgFAOQgHAPgLALIjRDSIjUhsIBqDWIjRDQQgKALgPAGQgPAGgQAAQgOAAgPgGgAiWCIQAFACADAEQAGAFABAIQACAIgEAHIheDEQABAEADAEIC+C8QAHAIAKAFQAKADAKAAQALAAAKgDQAKgFAIgIIDEjDIhjjGQgEgHABgIQACgIAGgFQAEgEAEgCQAFgCAFAAQAFAAAGADIDFBkIDEjFQAHgIAFgKQADgKAAgLQAAgKgDgKQgFgKgHgIIjEjEIjFBiQgGADgFAAQgGAAgEgCQgEgCgEgEQgGgFgCgIQgBgIAEgHIBjjFIjEjDQgIgIgKgFQgKgDgLAAQgKAAgKADQgKAFgHAIIjCDBIBiDKQAEAHgCAIQgBAHgFAGIgIAGQgFABgFAAQgFAAgGgCIjKhiIjODTQgDAKAAAKQAAALADAKQAFAKAIAIIDDDEIDEhiQAFgDAGAAQAFAAAEACg");
	this.shape_93.setTransform(600,75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_71,p:{scaleX:0.013,scaleY:0.013}}]},60).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[{t:this.shape_79}]},1).to({state:[{t:this.shape_80}]},1).to({state:[{t:this.shape_81}]},1).to({state:[{t:this.shape_82}]},1).to({state:[{t:this.shape_83}]},1).to({state:[{t:this.shape_84}]},1).to({state:[{t:this.shape_85}]},1).to({state:[{t:this.shape_86}]},1).to({state:[{t:this.shape_87}]},1).to({state:[{t:this.shape_88}]},1).to({state:[{t:this.shape_89}]},1).to({state:[{t:this.shape_90}]},1).to({state:[{t:this.shape_91}]},1).to({state:[{t:this.shape_92}]},1).to({state:[{t:this.shape_93}]},1).to({state:[{t:this.shape_71,p:{scaleX:0.064,scaleY:0.064}}]},1).to({state:[{t:this.shape_71,p:{scaleX:0.064,scaleY:0.064}}]},12).wait(20));

	// Layer 1
	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#B79CAA").s().p("EAS2ByHMgS2g5cMgTMA5cMhKrAAAQkGAAjwhmQjphjizi0Qi0izhjjpQhmjwAAkHMAAAhDuQAAjNB4ilQB3inDBhBMAyHgQ6Mg43gS1MAAAhK3QAAkGBmjwQBjjpC0izQCzi0DphjQDwhmEGAAMBJpAAAMAUOA6EMAUPg6EMBJoAAAQEHAADwBmQDpBjCzC0QC0CzBjDpQBmDwAAEGMAAABK3Mg5QAS1MA5QATMMAAABK2QAAEHhmDwQhjDpi0CzQizC0jpBjQjwBmkHAAgEAABAybQCBAABpBMQBoBNApB6MARbA1JMBGgAAAQCzAACjhEQCjhECAh/QB/iABEijQBEijAAizMAAAhGXMg0/gRxQh7gphLhqQhMhoABiBQABiBBLhpQBNhoB6gpMA09gRaMAAAhGVQAAiyhEijQhEijh/iAQiAh/ijhEQijhEizAAMhFMAAAMgSxA14QgrB4hnBLQhoBJiAABQh/gBhohJQhohLgqh4MgSyg14MhFMAAAQiyAAijBEQijBEiAB/Qh/CAhECjQhECjAACyMAAABGWMA0lARaQB7AoBLBpQBMBpAACAQABCBhMBoQhLBqh6ApMgyGAQ7QhJAYgrA+QgtA+AABLMAAABDuQAACzBECjQBECjB/CAQCAB/CjBEQCjBECyAAMBGLAAAMARyg1LQAph7BohKQBohMCBAAg");
	this.shape_94.setTransform(600,75,0.018,0.019);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#B79CAA").s().p("AAYCUIgYhLIgYBLIhhAAQgGAAgEgCQgEgBgEgFQgEgDgCgFQgCgEAAgGIAAhYQAAgEACgDQADgEAEgBIBBgWIhKgYIAAhhQAAgGACgEQACgFAEgEQAEgDAEgCQAEgCAGAAIBfAAIAaBLIAahLIBgAAQAFAAAFACQAEACAFADQADAEACAFQACAEAAAGIAABhIhLAYIBLAZIAABhQAAAGgCAEQgCAFgDADQgFAFgEABQgFACgFAAgAABBBIAEACIACAEIABABIAWBDIABABIBbAAIAFgBIABAAIAFgDIABgBIADgEIACgDIABgEIAAgDIAAhaIAAgBIhFgWIAAAAIgDgDIgBgBIgBgDIAAgBIAAgCIACgDIAEgCIA/gVIAFgDIAAhWIAAgFIAAgCIgCgFIgDgEIgBgBIgGgEIgGgCIgBAAIhZAAIAAABIgYBFIgBACIgCACIgBABIgEACQgCAAgCgDQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIgBgCIgYhGIhbAAIgGACQgDABgHAKIgBAGIAABbIBEAXIABABIADACIACACIAAACIAAACIgCACIAAABIgDADIgBAAIhBAVIgBACIgBAAIAAABIgBADIAABWIAAABIABAGIABABIADAGIAGAEIABAAIAGABIBbAAIABgBIAWhDIABgCIACgDIABgBIADgBIABAAg");
	this.shape_95.setTransform(600,75);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#B79CAA").s().p("AAaCiIgahSIgbBSIhpAAQgGAAgFgCIgJgHQgEgDgCgGQgCgFAAgGIAAhgQAAgFACgEQADgDAEgBIBHgYIhQgaIAAhqQAAgFACgGQACgFAEgEIAJgHQAFgBAGAAIBoAAIAcBRIAchRIBpAAQAFAAAFABQAFADAFAEIAGAJQACAGAAAFIAABqIhRAaIBRAbIAABqQAAAGgCAFQgDAGgDADQgFAEgFADQgFACgFAAgAABBHIAFACIACADIAAACIAZBKIAAABIBkAAQADAAADgCIABAAIAEgDIACgCIAEgEIABgCIABgFIAAgDIAAhhIAAgBIhKgZIAAgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgCgBIgBgDIAAgBIABgDIACgCIAFgDIBFgXIAEgDIAAheIAAgFIAAgDIgCgEQgBgDgBgBIgCgCQgDgDgDgBQgEgCgDAAIgBAAIhhAAIAAABIgbBLIAAADIgDACIgBABIgEAAQgCAAgCgBIgDgDIgBgCIgbhMIhiAAQgDAAgDACQgEABgHAKQgCAEAAADIAABjIBKAZIACABQAAAAABAAQAAABABAAQAAAAAAABQAAAAABAAIABACIAAADIABACIgCACIAAABIgDAEIgCAAIhFAXIgBAAIgCACIgBABIAAABIgBACIAABdIAAACIACAGIAAABIAEAHIAHAEIABAAQADACADAAIBjAAIAAgBIAZhKIABgCIADgDIABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAAAAAIABAAg");
	this.shape_96.setTransform(600,75);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#B79CAA").s().p("AAcCuIgchYIgcBYIhzAAQgGAAgFgBQgGgDgEgFQgFgDgCgHQgDgFABgGIAAhoQAAgFACgEQADgEAFgBIBMgaIhWgcIAAhyQgBgHADgFQACgGAFgFQAEgEAGgCQAFgCAGgBIBxAAIAeBZIAfhZIBwAAQAHABAFACQAGACAFAEQAEAFACAGQADAFAAAHIAAByIhYAcIBYAdIAABzQAAAGgDAFQgCAHgEADQgFAFgGADQgFABgHAAgAABBNIAFACIACAEIABABIAaBQIABABIBrAAQAEAAAEgCIAAAAIAGgDIACgCIADgEIABgDQABgDAAgDIAAgCIAAhqIAAgBIhQgbIgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIgBgBIgBgEIAAgBIAAgDIACgDIAGgDIBKgZIAEgDIAAhmIAAgFIAAgEIgCgDIgDgGIgBgBQgDgDgEgBIgIgCIAAAAIhpAAIgBABIgcBRIgBACIgCACIgBABQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIAAAAQgCAAgDgCQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBgBAAIgBgCIgchSIhrAAIgHACQgDABgJALIAAAIIAABrIBPAbIACABIACABIACADIAAADIABACIgCADIgBABIgCADIgCAAIhMAaIgCACIgBABIAAABIAAACIAABmIAAABIAAAHIABACQABADAEADIAGAEIABAAQADACAEAAIBrAAIABgBIAahQIABgBQABgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAIABAAQACgCACAAIABAAg");
	this.shape_97.setTransform(600,75);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#B79CAA").s().p("AAfC8IgfhfIgfBfIh7AAQgGAAgGgDQgGgDgFgEQgEgFgDgGQgDgGAAgHIAAhvQAAgGAEgEQACgEAGgBIBSgcIhegeIAAh8QAAgGADgHQADgGAEgEQAFgFAGgDQAGgCAGAAIB5AAIAhBfIAihfIB4AAQAHAAAGACQAGADAFAFQAEAEADAGQACAHABAGIAAB8IhfAeIBfAfIAAB7QgBAHgCAGQgDAGgEAFQgFAEgGADQgGADgHAAgAABBTIAFACIABAAIACAEIABACIAcBWIABABIBzAAQAEAAAEgCIABgBIAGgDIACgCIAEgFIABgDIABgGIAAgDIAAhyIAAgBIhXgdIAAAAQgDgBgBgCIgBgBIgCgFIAAgBIABgDIADgDIAAAAIAHgEIBPgZIAEgFIAAhtIAAgFIAAgFIgCgEIgEgFIgBgBQgEgEgEgBQgDgCgFAAIgBAAIhwAAIAAABIgfBXIgBADIgDACIgBABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIAAAAQgCAAgEgCIgDgEIAAgCIgfhYIhyAAQgEAAgEACQgEABgIAMIgCAIIAAB0IBVAcIACABQABAAAAABQABAAAAAAQABAAAAABQAAAAABABIACACIAAADIAAACIgBAEIgBABIgEADIgCABIhRAbIgCACIgBABIAAACIgBACIAABtIAAACQAAAEACADIAAACIAEAHIAHAFIABAAQAEACAFAAIBzAAIAAgBIAdhWIAAgCIADgEIACgBQACgBACAAIABAAg");
	this.shape_98.setTransform(600,75);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#B79CAA").s().p("AAhDJIghhlIghBlIiDAAQgIAAgGgCQgGgEgFgFQgGgEgCgHQgCgGAAgIIAAh3QAAgFACgFQAEgFAFgCIBYgdIhjghIAAiDQAAgIACgGQACgGAGgFQAFgGAGgCQAGgDAIAAICBAAIAjBmIAjhmICCAAQAHAAAGADQAHACAFAGQAFAFACAGQADAGAAAIIAACDIhlAhIBlAiIAACDQAAAIgDAGQgCAHgFAEQgFAFgHAEQgGACgHAAgAABBZQADAAADACIAAAAIADAFIABACIAeBcIABAAIB7AAQAEAAAEgCIACAAIAFgFIADgBIAEgGIABgDIABgGIAAgEIAAh4IgBgCIhbgfIgBAAQgDgBgCgCIgBgCIgBgEIAAgBIABgEIADgDIABAAQADgDADgBIBWgcIADgFIAAh1IAAgGIgBgEIgBgEQgCgDgCgCIgBgCQgDgDgFgCQgEgCgEAAIgCAAIh4AAIgBABIggBcIgCADIgCAEIgBABQgDABgDAAIAAAAQgCABgEgDIgDgEIgBgCIghheIh6AAQgEAAgEACQgEACgKAMIgCAJIAAB7IBcAfIACABQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAIACADIABADIAAADIgCADIAAACIgFADIgBAAIhXAeIAAAAIgDACIgBACIAAABIgBACIAAB1IAAACQABAEABAEIAAABIAGAIIAIAFIABAAQADACAFAAIB6AAIACAAIAehcIABgDQABgCACgCIABAAIAFgCIABAAg");
	this.shape_99.setTransform(600,75);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#B79CAA").s().p("AAjDWIgjhrIgjBrIiMAAQgIAAgHgDQgGgDgGgFQgFgFgDgHQgDgHAAgIIAAh/QAAgGADgFQAEgFAGgCIBdgfIhqgiIAAiNQAAgHADgIQADgGAFgGQAGgFAGgDQAHgDAIAAICKAAIAlBtIAmhtICKAAQAHAAAHADQAHADAFAFQAFAGADAGQAEAIAAAHIAACNIhsAiIBsAkIAACMQAAAIgEAHQgDAHgFAFQgFAFgHADQgHADgHAAgAABBeQADABADACIAAABIAEAEIAAACIAgBiIABAAICEAAQAEAAAFgCIABAAQAEgCACgCIADgCIAEgGIABgEIACgGIAAgEIAAiBIgBgBIhighIgBAAQgDgBgCgCIgBgDIgBgEIAAgCIABgEIADgDIABAAIAHgEIBbgeIAEgFIAAh9IgBgGIAAgFIgCgEIgEgGIgCgBQgDgEgFgBQgEgDgFAAIgBAAIiAAAIgBABIgiBjIgCAEIgDADIgBABQgDABgDAAIAAAAQgDAAgDgCQgDgCgBgCIgBgDIgjhkIiCAAQgFAAgEADQgEABgKANQgCAFAAAFIAACEIBhAgIACABQABAAAAABQABAAAAAAQABABAAAAQABAAAAABIACACIABADIAAAEIgCAEIAAACIgFADIgCAAIhcAgIgBAAIgCACIgCACIAAABIAAADIAAB8IAAACIACAIIAAACIAFAIIAJAFIABAAQAEACAFAAICDAAIAAAAIAhhiIABgCQABgDADgCIABAAQACgDADAAIABAAg");
	this.shape_100.setTransform(600,75);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#B79CAA").s().p("AAlDjIglhyIglByIiVAAQgIAAgHgDQgIgDgFgGQgGgFgDgIQgDgHAAgIIAAiHQAAgHADgFQAFgFAFgCIBkghIhxglIAAiVQAAgIADgIQADgHAGgFQAFgGAIgDQAHgDAIAAICTAAIAnBzIAohzICTAAQAIAAAHADQAIADAFAGQAGAFACAHQAEAIAAAIIAACVIhyAlIByAmIAACVQAAAIgEAHQgCAIgGAFQgFAGgIADQgHADgIAAgAAABkQAEAAAEADIAAAAQACACABADIACACIAhBoIABABICMAAQAEAAAFgCIACgBIAHgFIACgBIAEgHIACgEIACgHIAAgEIAAiJIgCgBIhogjIgBAAQgCgBgCgDIgCgBIgCgGIABgCIABgDIAEgEIAAAAIAJgEIBgggIAEgGIAAiEIgBgGIgBgFIgCgFIgEgGIgCgCQgDgDgFgCQgFgCgFAAIgBAAIiHAAIgCABIgkBoIgCAEIgDAEIgCABIgGACIAAAAQgDAAgEgDQgDgCAAgDIgBgCIgmhqIiKAAQgEAAgGACQgDACgLAOQgDAFAAAFIAACMIBoAiIACABQABAAAAABQABAAAAAAQABAAAAABQABAAAAABIACADIABACIABAEIgCAFIgBABIgGAEIgBABIhiAhIgDACIgCACIAAACIgBADIAACEIAAACIADAJIAAABIAFAJIAJAGIABAAQAFACAFAAICLAAIABgBIAjhnIABgDQAAgDADgCIABgBQADgCADAAIAAAAg");
	this.shape_101.setTransform(600,75);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#B79CAA").s().p("AAoDxIgoh6IgnB6IieAAQgIgBgIgDQgIgDgFgGQgHgGgCgHQgEgJAAgIIAAiPQAAgGAEgGQAEgFAGgCIBqgkIh4gnIAAidQAAgJAEgJQACgHAHgFQAFgHAIgDQAIgDAIgBICbAAIAqB7IArh7ICaAAQAJABAIADQAHADAGAHQAGAFADAHQAEAJAAAJIAACdIh5AnIB5AoIAACeQAAAIgEAJQgDAHgGAGQgGAGgHADQgIADgJABgAAABqQAEAAAEADIAAAAIAEAGIABACIAkBuIABAAICTAAQAFABAFgDIACAAIAHgGIADgBQADgDABgFIACgDIABgIIAAgEIAAiRIgBgBIhuglIAAAAQgEgBgCgDIgBgCIgCgFIABgCIABgFIAFgEIAAAAIAJgEIBlghIADgHIAAiMIAAgGIgBgFIgCgGIgFgFIgBgDQgDgDgGgCQgFgCgFAAIgCAAIiPAAIgBABIgmBuIgDADIgDAFIgBABQgDACgEAAIAAAAQgDAAgEgCQgDgCgBgEIgBgCIgohwIiRAAQgGAAgFACQgDABgNAQQgCAFAAAGIAACTIBtAkIACABIAFAEIACACIABADIAAAEQAAADgBADIgBABIgGAEIgCAAIhnAkIgBAAIgDACIgBADIgBABIAAADIAACMIAAACQAAAFACAEIABACQACAFAEAEQADADAGADIABAAQAFADAGgBICSAAIABAAIAlhtIABgDQABgEADgCIABAAQADgCADgBIAAAAg");
	this.shape_102.setTransform(600,75);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#B79CAA").s().p("AAqD9Igqh/IgqB/IimAAQgJAAgIgCQgIgFgGgFQgHgHgDgIQgDgIAAgKIAAiWQAAgHAEgGQAEgFAHgCIBvgmIh+gpIAAimQAAgJADgJQADgIAHgGQAGgHAIgDQAIgEAJABICkAAIAsCAIAtiAICjAAQAJgBAIAEQAJADAGAHQAGAGAEAIQADAJAAAJIAACmIh/ApIB/ArIAAClQAAAKgDAIQgEAIgGAHQgGAFgJAFQgIACgJAAgAAABwQAFABADACIABABQADACABADIABADIAmBzIABABICbAAQAGAAAFgDIACAAQAEgCAEgDIACgDIAFgHIACgEIABgIIAAgEIAAiZIgBgBIh0gnIgBgBQgEgBgCgCIgBgCIgBgGIAAgCIABgFQACgDADgBIAAgBIAJgEIBsgjIADgHIAAiUIAAgHIgBgFIgDgFQgBgDgDgEIgCgCQgEgDgFgCQgGgCgFgBIgCAAIiXAAIgCABIgoB0IgBAFIgEAEIgCABQgDADgDAAIgBAAQgDgBgFgDQgDgCgBgDIgBgDIgqh2IiZAAQgFABgGACQgEACgNAPQgCAFAAAHIAACcIBzAmIADABIADADIADADIABADIABAEIgCAGIgBACQgDADgDABIgCAAIhuAlIAAABIgDACIgBACIAAACIgBAEIAACTIAAACIACAKIABACQACAFAEAEIAKAGIABAAQAFADAGAAICaAAIABgBIAnhzIABgDQABgDADgDIABAAQAEgDADAAIAAAAg");
	this.shape_103.setTransform(600,75);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#B79CAA").s().p("AArELIgriHIgsCHIiuAAQgKAAgIgEQgJgEgHgGQgGgHgEgIQgDgJAAgKIAAieQgBgIAFgGQAFgGAGgCIB1gnIiEgrIAAivQAAgKADgJQAEgJAGgGQAHgGAJgEQAIgEAKAAICsAAIAuCIIAviIICsAAQAJAAAJAEQAJAEAGAGQAGAGAEAJQAFAJAAAKIAACvIiGArICGAsIAACvQAAAKgFAJQgEAIgGAHQgGAGgJAEQgJAEgJAAgAAAB2QAFAAADADIABAAQADACACAEIABADIAnB6IABAAICkAAQAGAAAGgCIACgBQAEgCAEgEIACgCQADgDACgFIACgEIABgIIAAgFIAAihIgBgBIh6gpIgBAAQgEgBgCgDIgCgDIgBgGIAAgCIACgFQACgDADgCIABAAIAJgEIByglIACgIIAAibIAAgHIgBgGIgCgFIgGgHIgBgCQgEgEgGgCQgGgCgFAAIgCAAIieAAIgCAAIgrB6IgCAFIgEAFIgBABQgDACgEAAIgBAAQgEAAgEgDQgEgCAAgDIgBgDIgth8IigAAQgHAAgGACQgEACgNAQQgCAGgBAHIAACkIB6AoIACABIAEADIADADIABADIABAFIgCAGIgBACQgDADgDABIgCABIh0AnIgEADIgBACIAAACIgBAEIAACbIAAACQABAFACAFIABACQACAFAEAFQAEAEAGADIABAAQAFACAIAAICiAAIABAAIAph6IABgDQAAgEAEgCIABgBQAEgCADAAIAAAAg");
	this.shape_104.setTransform(600,75);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#B79CAA").s().p("AAuEYIguiNIguCNIi3AAQgKAAgKgDQgIgFgHgHQgHgHgDgIQgFgJAAgLIAAimQABgIAEgGQAFgGAHgDIB7gpIiMgtIAAi4QAAgKAFgKQADgJAHgGQAHgHAIgEQAKgEAKAAIC1AAIAwCPIAyiPIC0AAQAJAAAKAEQAJAEAHAHQAGAGAFAJQADAKAAAKIAAC4IiMAtICMAvIAAC3QAAALgDAJQgFAIgGAHQgHAHgJAFQgKADgJAAgAAAB8QAFAAAEADIABABIAFAGIABADIApB/IACABICrAAQAGAAAGgDIACAAQAFgDADgEIADgCQADgEACgFIACgDIACgJIAAgFIAAipIgCgBIiAgrIgBAAQgDgBgDgEIgCgCQgBgDAAgDIABgDIABgFQADgEADgBIABgBIAKgEIB2gmIADgJIAAijIgBgHIgBgHIgCgFIgGgGIgBgDQgFgEgGgBQgFgDgGgBIgCAAIinAAIgCABIgsCAIgCAFIgEAFIgCABQgDADgEAAIgBAAQgEAAgFgDQgDgCgBgFIgCgCIguiDIioAAQgHABgGADQgEABgPARQgCAGAAAHIAACsIB/AqIACABQADABACADIADADIABADIABAFQAAADgCADIgBACQgDAEgEABIgCABIh5ApIgBAAIgDACIgBAEIAAACIgBADIAACiIAAADQAAAGACAFIABACIAHAKQAFAEAFADIABAAQAHADAHAAICqAAIABgBIAqh/IACgDQABgEADgDIABAAQAEgDAEAAIAAAAg");
	this.shape_105.setTransform(600,75);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#B79CAA").s().p("AAwElIgwiUIgwCUIjAAAQgKAAgKgEQgJgEgHgHQgIgHgDgKQgFgJABgLIAAiuQgBgIAFgHQAGgGAHgDICAgrIiRgwIAAjAQgBgLAFgJQADgKAIgHQAHgHAJgEQAKgEAKAAIC9AAIAzCVIA0iVIC9AAQAKAAAJAEQAKAEAHAHQAIAHADAKQAEAJABALIAADAIiUAwICUAxIAADAQgBALgEAJQgDAKgIAHQgHAHgKAEQgJAEgKAAgAAACBQAGABADADIABAAQAEADABAEIABADIAsCGIABAAIC0AAQAGAAAGgDIADAAQAFgDAEgEIADgCQADgEACgFIACgFIACgJIAAgFIAAiwIgCgBIiGgtIgBgBQgEgBgDgEIgBgCQgCgDAAgEIABgDIABgFQADgDAEgCIAAAAIALgFIB8goIADgJIAAirIgBgHIgCgHIgDgGIgEgHIgCgCQgFgEgGgCQgGgDgHAAIgBAAIivAAIgCAAIgvCGIgBAFQgCAEgDACIgCABQgDADgEAAIgBAAQgEAAgFgDQgEgDgBgEIgBgDIgxiIIiwAAQgHAAgGADQgEACgPASQgDAGAAAHIAAC1ICFAsIACABIAFADIADADIACAEIABAFIgDAGIgBACQgDAEgEACIgDAAIh+ArIgBABIgDACIgBADIgBACIAAAFIAACpIAAADQABAGACAFIAAACQADAGAEAFQAFAEAHADIAAAAQAGADAIAAICyAAIABAAIAtiFIABgEQABgEAEgDIABgBQAEgCAEgBIAAAAg");
	this.shape_106.setTransform(600,75);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#B79CAA").s().p("AAyEyIgyiaIgzCaIjIAAQgLAAgJgEQgKgEgIgIQgIgHgDgKQgEgKgBgLIAAi2QABgJAEgHQAGgGAHgDICGgtIiYgyIAAjJQABgLAEgKQADgKAIgHQAIgIAKgEQAJgEALAAIDFAAIA2CbIA2ibIDFAAQALAAAKAEQAKAEAHAIQAIAHAEAKQAEAKAAALIAADJIiZAyICZAzIAADJQAAALgEAKQgEAKgIAHQgHAIgKAEQgKAEgLAAgAAACHQAFAAAFADIABABQADADACAEIABAEIAtCLIACAAIC7AAQAIAAAGgCIACgBQAGgDAEgEIACgCQAEgFACgFIACgFQACgEgBgFIAAgGIAAi4IgCgBIiLgvIgBAAQgEgCgDgDIgCgDIgCgHIABgDIACgGQACgDAEgCIABAAIAMgFICBgqIACgKIAAiyIAAgIIgCgHIgCgGIgGgHIgBgCQgGgEgFgDQgHgCgHgBIgBAAIi2AAIgDABIgxCMIgCAFIgEAGIgCABQgEADgEAAIgBAAQgFAAgEgDQgEgDgCgEIgBgEIgyiOIi5AAQgHAAgGADQgGACgPATQgCAHgBAHIAAC9ICMAuIACABQADABACACIADADIACAEIAAAFIgBAIIgCACQgDADgEACIgEABIiDAtIAAAAQgEABgBACIgBADIgBACIAAAFIAACxIAAADQABAGACAGIABACQACAGAFAEQAFAFAHAEIABAAQAHACAHAAIC6AAIABAAIAviLIABgEQACgEAEgDIAAgBQAEgDAFAAIAAAAg");
	this.shape_107.setTransform(600,75);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#B79CAA").s().p("AA1E/Ig1ihIg1ChIjRAAQgLABgKgFQgKgEgIgIQgJgIgDgLQgFgJABgMIAAi+QgBgJAFgHQAGgHAIgDICMgvIieg0IAAjRQgBgMAFgLQADgKAJgIQAIgHAKgFQAKgFALAAIDPAAIA3CjIA4ijIDOAAQALAAALAFQAKAFAIAHQAIAIAEAKQAFALAAAMIAADRIigA0ICgA2IAADRQAAAMgFAJQgEALgIAIQgIAIgKAEQgLAFgLgBgAAACNQAGABAEADIABAAQAEADABAFIACADIAvCRIACABIDDAAQAHAAAIgDIABgBQAGgCAFgFIADgCIAFgKIACgFQACgFAAgGIAAgFIAAjAIiUgxIgBgBQgFgCgCgEIgCgCQgCgEABgEIAAgDIACgGQADgEAEgCIAAAAIANgEICHgtIACgKIAAi5IgBgJIgCgHIgDgGIgFgIIgCgCQgEgEgHgCQgHgEgHAAIgCAAIi+AAIgCAAIgzCTIgCAFQgBADgEADIgCACQgDADgFAAIgBAAQgFAAgFgEQgEgDgCgFIgBgDIg1iUIjAAAQgHAAgHAEQgFABgRAUQgCAHAAAIIAADFICRAwIACAAQADACADACIADADIABAEIABAGQAAADgCAEIgBACQgDAEgFADIgDAAIiJAvIgBAAIgEADIgBAEIgBACIAAAEIAAC5IAAADQAAAHACAGIABACQADAGAFAEQAGAFAGAEIABAAQAIADAHAAIDCAAIACgBIAwiQIABgEQACgFAEgDIABAAQAEgDAFgBIAAAAg");
	this.shape_108.setTransform(600,75);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#B79CAA").s().p("AA2FNIg2ioIg3CoIjZAAQgMAAgLgFQgKgFgJgIQgIgIgEgLQgFgLAAgMIAAjFQAAgJAGgIQAFgHAIgDICTgxIimg2IAAjaQAAgNAFgLQAEgKAIgIQAJgIAKgFQALgFAMAAIDWAAIA6CpIA7ipIDWAAQAMAAAKAFQAMAFAHAIQAJAIAEAKQAFALAAANIAADaIinA2ICnA3IAADaQAAAMgFALQgEALgJAIQgHAIgMAFQgKAFgMAAgAAACTQAGAAAFADIABABQADADACAFIABAEIAyCXIACAAIDLAAQAIAAAHgDIACgBQAGgDAFgEIADgDQADgEADgGIACgFQABgFAAgGIAAgGIAAjHIiZg0IgBgBQgFgCgDgEIgCgCIgCgIIABgDIACgHQADgEAFgCIAAAAIANgFICNguIABgLIAAjBIAAgIIgCgIIgDgGIgGgIIgBgCQgGgFgHgCQgGgDgIAAIgCAAIjJAAIg0CYIgDAFQgBAEgDADIgCACQgEADgFAAIgBAAQgFAAgFgEQgEgDgCgFIgCgDIg3iaIjHAAQgIAAgIADQgEACgRAUQgEAIAAAIIAADMICXAyIADABQADABACADIAEADIACAEIABAGQAAAEgDAEIgBACQgEAFgFACIgDAAIiPAxIAAAAIgEAEIgCADIAAADIgBAEIAADBIAAADQABAHADAGIABACQACAGAGAFQAEAGAIADIABAAQAHADAJAAIDJAAIACAAIAyiXIACgEQACgFAEgDIABgBQAEgDAFAAIAAAAg");
	this.shape_109.setTransform(600,75);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#B79CAA").s().p("AA4FaIg4ivIg5CvIjiAAQgNAAgLgFQgKgFgJgIQgJgJgEgLQgFgLAAgNIAAjNQAAgKAFgIQAGgHAJgDICYgzIisg4IAAjjQAAgNAFgLQAEgLAJgJQAJgIAKgFQALgFANAAIDeAAIA9CwIA9iwIDfAAQAMAAALAFQAMAFAHAIQAKAJAEALQAFALAAANIAADjIiuA4ICuA6IAADiQAAANgFALQgEALgKAJQgHAIgMAFQgLAFgMAAgAAACZQAHAAAEADIACABQADADACAFIABAEIAzCdIACABIDUAAQAIAAAHgDIADgBQAGgDAFgFIACgDQAEgFADgGIACgFIACgLIAAgGIAAjQIigg2IgCAAQgEgCgDgEIgDgDQgBgEAAgEIAAgEIADgGQADgEAFgCIAAgBIAOgFICSgwIACgLIAAjJIgBgJIgCgIIgDgGIgGgIIgCgCQgFgFgIgCQgGgEgIAAIgBAAIjSAAIg3CeIgCAGQgBAEgDADIgDACQgDADgGAAIgBAAQgFAAgGgEQgEgDgCgFIgCgEIg4igIjQAAQgIAAgIAEQgFACgSAVQgDAHAAAJIAADVICdA0IADABQADABACACIAEAEIACAEQABADAAADIgCAIIgCADQgDAEgGACIgDABIiUAzIgBAAQgDABgCACIgBAEIAAADIgBAFIAADIIAAADIADANIABADQADAGAFAFQAGAGAIAEIABAAQAHADAJAAIDRAAIACgBIA0icIACgFQACgFAEgDIABgBQAFgDAFAAIAAAAg");
	this.shape_110.setTransform(600,75);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#B79CAA").s().p("AA7FnIg7i1Ig7C1IjrAAQgMAAgMgFQgLgFgKgIQgIgJgFgMQgFgMAAgNIAAjUQAAgLAFgIQAHgIAJgDICdg1Iiyg7IAAjrQAAgNAFgMQAFgLAIgJQAKgJALgFQAMgFAMAAIDnAAIA/C2IA/i2IDoAAQAMAAAMAFQAMAFAIAJQAJAJAFALQAFAMAAANIAADrIi0A7IC0A8IAADrQAAANgFAMQgFAMgJAJQgIAIgMAFQgMAFgMAAgAAACeQAHABAEAEIACAAQADAEACAFIACAEIA1CjIADABIDbAAQAIAAAIgEIACgBQAHgDAFgFIADgDQAEgFACgGIADgFQABgGAAgGIAAgHIAAjXIimg3IgBgBQgGgDgDgEIgCgDQgBgDAAgFIABgEIACgGQAEgFAEgCIABAAIAOgGICYgxIABgMIAAjRIgBgJIgCgIIgDgGIgHgJIgBgCQgGgEgHgDQgHgEgIAAIgCAAIjZAAIg5CkIgCAGQgCAEgDADIgCACQgEADgGAAIgBAAQgFAAgGgDQgFgEgCgFIgBgEIg8imIjXAAQgIAAgIAEQgFACgTAVQgDAJAAAIIAADeICjA1IACABIAGAEIAEAEIABAEIACAGQAAAFgCAEIgCACQgDAFgGADIgDAAIibA1IgBAAQgDABgBACIgBAFIgBACIAAAGIAADPIAAADQAAAIADAGIABADQADAGAGAFQAFAGAIAEIABAAQAIAEAJAAIDaAAIACgBIA2ijIABgEQACgGAFgDIABAAQAFgEAFgBIAAAAg");
	this.shape_111.setTransform(600,75);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#B79CAA").s().p("AA9F0Ig9i7Ig+C7IjzAAQgNAAgMgFQgMgFgJgJQgKgKgEgMQgFgMAAgNIAAjdQAAgKAFgJQAHgIAJgDICjg3Ii4g9IAAj0QAAgNAFgNQAEgLAKgJQAJgKAMgFQAMgFANAAIDwAAIBBC9IBBi9IDwAAQANAAANAFQAMAFAIAKQAKAJAFALQAFANAAANIAAD0Ii6A9IC6A+IAAD0QAAANgFAMQgFAMgKAKQgIAJgMAFQgNAFgNAAgAAACkQAHAAAFAEIABACQAEADACAFIACAEIA3CpIACABIDjAAQAJAAAIgEIADgBQAGgDAGgFIACgDQAFgFACgHIADgGQABgFAAgHIAAgGIAAjfIisg6IgBgBQgFgCgEgEIgCgEIgCgIIABgEIADgHQADgFAGgCIAAAAIAPgGICdgzIABgNIAAjYIgBgJIgCgJIgDgGIgHgJIgBgCQgGgFgIgDQgHgDgIgBIgCAAIjdAAIgEABIg7CpIgCAHIgFAHIgDACQgEADgGABIgBAAQgGAAgGgFQgEgDgCgGIgCgEIg+isIjfAAQgJAAgIAEQgFACgUAXQgDAIAAAJIAADlICpA4IACABQAEABADADIAEAEIABAEQACAEAAADQAAAFgCAEIgCADQgEAEgGADIgDABIigA2IgBAAIgFAEIgBAEIgBADIAAAFIAADYIAAADQABAIACAGIACADQADAHAFAFQAGAGAIAEIABAAQAJAEAJAAIDhAAIADgBIA4ioIACgFQACgGAEgDIABgBQAFgDAGgBIAAAAg");
	this.shape_112.setTransform(600,75);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#B79CAA").s().p("AA/GBIg/jCIhADCIj8AAQgNAAgNgFQgMgGgJgJQgKgJgFgNQgGgMAAgOIAAjlQABgLAFgJQAIgIAJgDICpg5IjAg/IAAj9QAAgOAGgNQAFgMAKgJQAJgJAMgGQANgFANAAID5AAIBDDEIBEjEID4AAQAOAAAMAFQANAGAJAJQAJAJAGAMQAFANABAOIAAD9IjCA/IDCBAIAAD9QgBAOgFAMQgGANgJAJQgJAJgNAGQgMAFgOAAgAAACqQAHAAAGAEIABACQAEADACAFIACAFIA5CvIACAAIDrAAQAJAAAIgDIAEgCQAGgDAGgFIACgDQAFgGADgHIACgGQACgGAAgGIAAgHIAAjnIiyg8IgBAAQgGgCgDgFIgDgDQgBgEgBgFIABgFIADgHQADgFAHgCIAAAAIAPgGICjg1IABgNIAAjgIgBgJIgDgJIgCgHIgHgJIgCgCQgHgFgHgDQgIgEgJAAIgBAAIjlAAIgEAAIg9CvIgDAHIgEAIIgEACQgEADgGABIgBAAQgGAAgGgFQgFgDgCgGIgBgEIhAiyIjoAAQgJAAgIAEQgFACgVAXQgDAJAAAJIAADuICuA5IADABIAHAEIAEAEIACAFQABAEAAADQAAAFgCAEIgBADQgFAFgGACIgEABIilA5IAAAAQgEABgCADIgBAEIgBADIAAAGIAADeIAAAEQABAIACAHIABACQAEAIAFAFQAHAGAIAFIABAAQAIADAKAAIDqAAIACAAIA7ivIABgFQACgFAFgEIABgBQAFgEAGAAIAAAAg");
	this.shape_113.setTransform(600,75);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#B79CAA").s().p("ABBGOIhBjIIhBDIIkFAAQgPAAgMgFQgNgFgKgKQgKgKgEgNQgHgNAAgPIAAjrQAAgMAHgJQAHgJAKgEICug6IjGhBIAAkFQAAgPAHgNQAEgNAKgJQAKgKANgGQAMgFAPAAIEAAAIBGDKIBGjKIEBAAQAOAAANAFQANAGAJAKQAKAJAGANQAFANAAAPIAAEFIjHBBIDHBCIAAEFQAAAPgFANQgGANgKAKQgJAKgNAFQgNAFgOAAgAAACwQAHAAAGAFIACABQADADACAGIADAFIA6C1ID2AAQAJAAAJgEIADgBQAHgEAGgGIADgCQAFgGACgHIADgGQACgGAAgHIAAgHIAAjuIi5g/IgCgBQgFgBgEgGIgCgDIgCgJIABgFIADgHQAEgFAFgCIABAAIAQgGICpg3IABgOIAAjnIgCgLIgDgJIgDgGIgHgKIgCgCQgFgFgIgEQgJgDgIgBIgDAAIjsAAIgEABIg/C1IgDAHQgBAFgEAEIgDABQgEAEgHABIgBAAQgGgBgGgFQgGgDgBgGIgCgFIhCi4IjvAAQgKAAgIAEQgGADgVAYQgEAJAAAKIAAD2IC1A7IADABIAHAEIADAEIADAFQABADAAAEQAAAFgCAFIgCACQgEAGgGACIgEABIirA7IgBAAQgDABgCADIgCAFIgBACIAAAGIAADmIAAAEQABAJADAGIACADQADAIAFAFQAHAGAJAFIABAAQAIAEALAAIDzAAIA9i1IACgFQABgGAGgDIABgBQAEgEAHgBIAAAAg");
	this.shape_114.setTransform(600,75);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#B79CAA").s().p("ABEGcIhEjQIhEDQIkNAAQgPAAgOgGQgMgGgKgKQgKgKgGgNQgFgOAAgPIAAj0QgBgLAHgKQAHgJAKgEIC1g8IjMhDIAAkOQAAgPAFgOQAGgNAKgKQAKgKAMgGQAOgGAPAAIEJAAIBIDSIBIjSIEKAAQAOAAAOAGQANAGAKAKQAKAKAFANQAHAOAAAPIAAEOIjOBDIDOBFIAAENQAAAPgHAOQgFANgKAKQgKAKgNAGQgOAGgOAAgAAAC2QAHAAAHAEIABACQAEADADAGIABAFIA9C7ID+AAQAJAAAKgEIACgBQAIgEAGgGIADgDQAFgGADgHIACgGQACgHAAgGIAAgIIAAj2Ii/hAIgBgBQgGgCgDgFIgDgEQgCgEAAgFIABgFIADgIQAEgFAGgCIABgBIARgFICtg5IABgPIAAjvIgCgKIgCgJIgEgHIgGgKIgDgCQgGgGgIgDQgIgEgJAAIgCAAIj6AAIhAC7IgDAIQgCAFgDADIgDACQgGAEgFAAIgCAAQgGAAgHgFQgFgEgCgFIgCgFIhEi+Ij3AAQgKAAgJAEQgFACgWAZQgEAKAAAKIAAD9IC7A+IACABQAEABAEADIADAEIADAFIACAIQgBAFgCAFIgCADQgEAFgHADIgDABIixA8IgBAAQgEACgCACIgCAFIAAADIAAAGIAADuIAAAEQABAIADAIIABADQAEAHAGAGQAGAHAJAEIACAAQAIAEALAAID8AAIA+i6IACgGQACgGAFgEIABgBQAGgEAGAAIAAAAg");
	this.shape_115.setTransform(600,75);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#B79CAA").s().p("ABGGpIhGjWIhGDWIkWAAQgPAAgOgGQgOgGgJgKQgMgLgEgOQgHgNAAgQIAAj8QAAgMAHgJQAIgKAKgEIC6g+IjThFIAAkXQAAgQAHgOQAEgNAMgKQAJgLAOgGQAOgGAPAAIESAAIBKDYIBLjYIESAAQAOAAAOAGQAPAGAJALQALAKAGANQAGAOAAAQIAAEXIjVBFIDVBHIAAEWQAAAQgGANQgGAOgLALQgJAKgPAGQgOAGgOAAgAAAC8QAHAAAHAEIACACQADADADAHIACAEIA/DBIEGAAQAKAAAJgDIADgCQAIgEAGgGIADgDQAFgGADgHIACgHQACgHAAgHIAAgHIAAj/IjEhCIgCAAQgGgDgEgFIgCgEQgCgEAAgFIABgFQABgEACgEQAEgGAHgCIABgBIARgFICzg7IAAkGIgBgKIgDgKIgDgHIgIgKIgBgCQgIgGgIgDQgIgEgKAAIgBAAIkCAAIhCDBIgDAHQgDAFgDAEIgDACQgFAEgGABIgCAAQgHAAgGgFQgGgFgCgGIgCgEIhGjEIj/AAQgKAAgJAEQgGACgXAaQgDAKAAAKIAAEGIDAA/IADABIAHAEIAFAFIACAFQACAEgBAEQAAAFgBAFIgCADQgGAGgGACIgEABIi2A/IgBAAQgEABgCADIgBAFIgBADIAAAHIAAD1IAAAEQAAAJADAHIACADQADAIAHAGQAGAHAKAFIABAAQAJADALAAIEEAAIBAjAIACgFQACgHAGgEIABgBQAFgEAHAAIAAAAg");
	this.shape_116.setTransform(600,75);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#B79CAA").s().p("ABIG2IhIjdIhJDdIkeAAQgPAAgPgGQgOgHgKgKQgLgLgGgOQgGgOAAgQIAAkEQAAgMAHgKQAHgKAMgEIDAhAIjahIIAAkfQAAgQAGgPQAGgNALgLQAKgKAOgHQAPgGAPAAIEbAAIBMDfIBNjfIEaAAQAPAAAPAGQAOAHAKAKQAMALAFANQAHAPAAAQIAAEfIjcBIIDcBJIAAEfQAAAQgHAOQgFAOgMALQgKAKgOAHQgPAGgPAAgAAADBQAIAAAGAFIACACQAFAEACAGIACAFIBADHIEOAAQALAAAJgEIAEgCQAHgDAHgHIADgDQAFgGADgIIADgHQACgHAAgHIAAgIIAAkGIjLhEIgCgBQgGgCgEgGIgCgEQgCgEAAgFIABgFQAAgFADgEQAEgGAHgCIABAAIARgGIC6g9IAAkOQgBgFgBgFIgCgLIgEgHIgIgKIgCgCQgHgGgJgDQgIgEgKgBIgCAAIkJAAIhFDHIgCAIQgDAFgEAEIgCADQgGAEgGAAIgCAAQgGAAgIgFQgFgFgDgGIgCgFIhIjKIkHAAQgKAAgKAFQgGACgWAaQgFAKAAALIAAEOIDGBBIAEABQAEACADADIAEAEIADAFQACAFAAAEQAAAFgDAFIgCADQgEAGgHADIgFABIi8BAIgBABQgDABgCADIgCAFIgBADIAAAHIAAD9IAAAEQACAJADAIIABADQADAIAHAGQAGAHALAFIAAAAQAKAEALAAIEMAAIBCjGIACgGQADgHAFgEIABgBQAGgEAHgBIAAAAg");
	this.shape_117.setTransform(600,75);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#B79CAA").s().p("ABKHDIhKjjIhKDjIknAAQgQAAgPgGQgOgHgLgKQgMgMgFgOQgHgPAAgQIAAkMQAAgMAHgLQAIgKALgEIDGhCIjghKIAAkoQAAgQAHgPQAFgOAMgLQALgLAOgHQAPgGAQAAIEiAAIBPDlIBQjlIEiAAQAQAAAPAGQAOAHALALQAMALAFAOQAHAPAAAQIAAEoIjiBKIDiBLIAAEoQAAAQgHAPQgFAOgMAMQgLAKgOAHQgPAGgQAAgAAPDMQAGAFADAHIBEDSIEWAAQALAAAKgEQAKgEAIgIQAIgIAEgKQAEgKAAgLIAAkWIjRhGQgHgDgFgGQgFgHAAgHQAAgIAFgGQAFgHAHgCIDRhFIAAkWQAAgLgEgKQgEgKgIgIQgIgIgKgEQgKgEgLAAIkRAAIhKDVQgCAHgHAFQgHAEgHAAQgHAAgGgEQgHgFgCgHIhKjVIkRAAQgLAAgKAEQgLAEgTAaQgEAKAAALIAAEWIDPBFQAIACAEAHQAFAGAAAIQAAAHgFAHQgEAGgIADIjFBDQgFABgDAEQgCAEAAAEIAAEMQAAALAEAKQAEAKAIAIQAHAIALAEQAKAEALAAIEVAAIBGjSQACgHAHgFQAGgFAHAAQAIAAAHAFg");
	this.shape_118.setTransform(600,75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_94}]},71).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_97}]},1).to({state:[{t:this.shape_98}]},1).to({state:[{t:this.shape_99}]},1).to({state:[{t:this.shape_100}]},1).to({state:[{t:this.shape_101}]},1).to({state:[{t:this.shape_102}]},1).to({state:[{t:this.shape_103}]},1).to({state:[{t:this.shape_104}]},1).to({state:[{t:this.shape_105}]},1).to({state:[{t:this.shape_106}]},1).to({state:[{t:this.shape_107}]},1).to({state:[{t:this.shape_108}]},1).to({state:[{t:this.shape_109}]},1).to({state:[{t:this.shape_110}]},1).to({state:[{t:this.shape_111}]},1).to({state:[{t:this.shape_112}]},1).to({state:[{t:this.shape_113}]},1).to({state:[{t:this.shape_114}]},1).to({state:[{t:this.shape_115}]},1).to({state:[{t:this.shape_116}]},1).to({state:[{t:this.shape_117}]},1).to({state:[{t:this.shape_118}]},1).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1131,81,138,138.1);
// library properties:
lib.properties = {
	width: 1200,
	height: 150,
	fps: 24,
	color: "#000000",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/Artwork47ai.png", id:"Artwork47ai"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;